from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

import yaml

from mship.core.config import RepoConfig, WorkspaceConfig, resolve_go_task_files


REPO_MARKERS = [
    ".git",
    "Taskfile.yml",
    "package.json",
    "go.mod",
    "pyproject.toml",
    "Cargo.toml",
    "build.gradle",
    "pom.xml",
]

SKIP_DIRS = {
    "node_modules",
    ".venv",
    "__pycache__",
    "dist",
    "build",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
}


@dataclass
class DetectedRepo:
    path: Path
    markers: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class TaskfileWriteResult:
    """Outcome of WorkspaceInitializer.write_taskfile.

    - wrote:    a fresh Taskfile.yml stub was written (dir had no go-task file).
    - existing: the go-task file that suppressed the stub (None when wrote)."""
    wrote: bool
    existing: Path | None = None

    @property
    def needs_rename(self) -> bool:
        """True when the existing go-task file is a non-`Taskfile.yml` spelling
        that go-task resolves but mship's stub-based tooling keys off `.yml`."""
        return self.existing is not None and self.existing.name != "Taskfile.yml"


class WorkspaceInitializer:
    """Detects repos, generates config, and scaffolds files."""

    def detect_repos(self, workspace_path: Path) -> list[DetectedRepo]:
        repos: list[DetectedRepo] = []

        # Check current directory itself
        current_markers = self._find_markers(workspace_path)
        if current_markers:
            repos.append(DetectedRepo(path=workspace_path, markers=current_markers))

        # Check immediate subdirectories
        for item in sorted(workspace_path.iterdir()):
            if not item.is_dir():
                continue
            if item.name.startswith("."):
                continue
            if item.name in SKIP_DIRS:
                continue
            markers = self._find_markers(item)
            if markers:
                repos.append(DetectedRepo(path=item, markers=markers))

        return repos

    def _find_markers(self, path: Path) -> list[str]:
        markers: list[str] = []
        for marker in REPO_MARKERS:
            target = path / marker
            if not target.exists():
                continue
            if marker == "Taskfile.yml" and self._is_generated_stub(target):
                # A dir whose only marker is mship's OWN generated stub Taskfile
                # must not be re-promoted to a repo on a later `init --detect`.
                # Match by content (not filename) so a hand-written Taskfile.yml
                # still counts. See issue #366 finding #1.
                continue
            markers.append(marker)
        return markers

    def _is_generated_stub(self, taskfile: Path) -> bool:
        try:
            return taskfile.read_text() == self.TASKFILE_TEMPLATE
        except OSError:
            return False

    TASKFILE_TEMPLATE = """\
version: '3'

# Starter stub generated by `mship init`. Every task FAILS on purpose (exit 1)
# so an unedited stub can never fabricate a passing `mship test`. Replace each
# `exit 1` with the real command for this repo. See issue 366 finding 1.
tasks:
  test:
    desc: Run tests (stub - replace exit 1 with your test command)
    cmds:
      - exit 1

  run:
    desc: Start the service (stub - replace exit 1 with your run command)
    cmds:
      - exit 1

  lint:
    desc: Run linter (stub - replace exit 1 with your lint command)
    cmds:
      - exit 1

  setup:
    desc: Set up development environment (stub - replace exit 1 with your setup command)
    cmds:
      - exit 1
"""

    def generate_config(
        self,
        workspace_name: str,
        repos: list[dict],
        env_runner: str | None,
    ) -> WorkspaceConfig:
        """Build and validate a WorkspaceConfig from user inputs."""
        repo_configs: dict[str, RepoConfig] = {}
        for repo in repos:
            repo_configs[repo["name"]] = RepoConfig(
                path=Path(repo["path"]),
                type=repo["type"],
                depends_on=repo.get("depends_on", []),
                git_root=repo.get("git_root"),
            )

        config = WorkspaceConfig(
            workspace=workspace_name,
            env_runner=env_runner,
            repos=repo_configs,
        )
        return config

    def write_config(self, path: Path, config: WorkspaceConfig) -> None:
        """Write mothership.yaml."""
        data: dict = {
            "workspace": config.workspace,
        }
        if config.env_runner:
            data["env_runner"] = config.env_runner

        repos_data: dict = {}
        for name, repo in config.repos.items():
            repo_data: dict = {
                "path": str(repo.path),
                "type": repo.type,
            }
            if repo.depends_on:
                serialized_deps = []
                for dep in repo.depends_on:
                    if dep.type == "compile":
                        serialized_deps.append(dep.repo)
                    else:
                        serialized_deps.append({"repo": dep.repo, "type": dep.type})
                repo_data["depends_on"] = serialized_deps
            repos_data[name] = repo_data
        data["repos"] = repos_data

        with open(path, "w") as f:
            yaml.dump(data, f, default_flow_style=False, sort_keys=False)

    def write_taskfile(self, repo_path: Path) -> TaskfileWriteResult:
        """Write a starter Taskfile.yml only when NO go-task file already resolves
        in `repo_path`. Returns a result describing what happened so callers can
        offer a rename for a non-`.yml` spelling instead of shadowing it with a
        generated `Taskfile.yml` stub. See issue #366 finding #1."""
        existing = resolve_go_task_files(repo_path)
        if existing:
            return TaskfileWriteResult(wrote=False, existing=existing[0])
        (repo_path / "Taskfile.yml").write_text(self.TASKFILE_TEMPLATE)
        return TaskfileWriteResult(wrote=True, existing=None)
