"""Serve-side execution of a go-task verb on THIS machine — the "remote" side
of `mship run/capture/build --remote[=role]` (see
specs/2026-07-11-remote-run-machine.md, MOS-191/MOS-203).

The client (a different mship workspace, Task 5) POSTs `{task, repos,
platform?, kind?}` to `POST /exec/{verb}` (registered in `core/serve.py`,
inheriting serve's bearer-auth dependency). This module is the generator
`run_verb_stream` that endpoint drives: it materializes the task's branch
worktree on this machine (the branch already exists on origin — pushed by
the operator's `mship spawn`/dispatch — this never creates a new branch),
runs the repo's go-task target with the same env-var contract as a local
run, and yields the subprocess's output incrementally so the client can
render it live.

Wire contract (Task 5's client parses this):
    - Every line yielded up to the last one is raw task output (stdout and
      stderr interleaved, one write per line, newline-terminated, UTF-8).
    - Any freeform notice lines (e.g. the MOS-203 base-freshness warning)
      are indistinguishable from task output on the wire — they're just
      more lines — so a client that renders every line live is correct by
      construction; nothing needs it to distinguish notice vs. task output.
    - CONTROL RECORDS are anti-spoof-tagged with a PER-REQUEST NONCE the
      task cannot predict (generated by `core/serve.py post_exec`, handed
      to the client out-of-band as the `X-Mship-Exec-Nonce` response header
      — sent before the streamed body, so the task can never inject it).
      Without the nonce tag a control line is just ordinary task output:
      a remote branch that prints a bare `__MSHIP_EXIT__ 0` can NOT
      green-wash a failed build.
    - For `verb == "capture"` ONLY, if the task exits 0 and produces at
      least one artifact (`capture.discover_artifacts` on the remote's
      `MSHIP_CAPTURE_DIR`), a length-prefixed tar block is emitted after
      that repo's task lines and before the exit sentinel:
          __MSHIP_ARTIFACTS__:<nonce> <byte_count>\\n
          <exactly byte_count bytes of UNCOMPRESSED tar, containing the
           discovered artifact files at their basenames, e.g. screen.png,
           layout.json>
      `<byte_count>` is a base-10 int. The client must read exactly that
      many raw bytes as the tar (binary-safe — do NOT line-split them)
      before resuming line-based reads. No block is emitted when capture
      produced no artifacts; instead a capture that exits 0 with NO
      recognized artifact is turned into an ERROR (an error line + a
      non-zero exit code), matching local `capture.run_capture`. `run`/
      `build` never emit an artifact block.
    - The LAST line always matches `__MSHIP_EXIT__:<nonce> <code>\\n` where
      <code> is a base-10 int (0 == success). This conveys the remote
      task's exit code as DATA, never as an HTTP error status — a non-zero
      task exit does not raise; the client must parse this trailing line
      (matched against its nonce) to learn the real result and mirror it as
      its own process exit code.
"""
from __future__ import annotations

import io
import queue
import shutil
import tarfile
import tempfile
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, Protocol

from mship.core import capture as _cap
from mship.core.config import WorkspaceConfig

VERBS: tuple[str, ...] = ("run", "capture", "build")

# Trailing sentinel line: `f"{EXIT_MARKER}:{nonce} {code}\n"` — the `:{nonce}`
# tag (a per-request secret handed to the client via the X-Mship-Exec-Nonce
# response header) is what stops task stdout from spoofing the exit code. See
# the module docstring for the full wire contract Task 5's client must parse.
EXIT_MARKER = "__MSHIP_EXIT__"

# Length-prefixed tar block marker (capture only):
# `f"{ARTIFACT_MARKER}:{nonce} {len(tar_bytes)}\n"` immediately followed by
# exactly that many raw (uncompressed) tar bytes. Nonce-tagged for the same
# anti-spoof reason as EXIT_MARKER. See module docstring for the full framing.
ARTIFACT_MARKER = "__MSHIP_ARTIFACTS__"


class UnknownVerbError(ValueError):
    """`verb` is not one of `VERBS`."""


class MaterializeError(Exception):
    """A git plumbing command needed to bring a repo's task-branch worktree
    up to date (fetch, checkout, reset, or worktree add) exited non-zero.

    Raised by `materialize_worktree`/`_run_checked` and caught by
    `run_verb_stream`, which turns it into a clean stream error (an error
    line naming the repo + failing command, then a non-zero `__MSHIP_EXIT__`)
    rather than silently running the task against a missing/stale worktree
    (Task 6 hardening — see the module docstring's wire contract)."""


class ShellLike(Protocol):
    """The subset of `mship.util.shell.ShellRunner` this module needs.
    `.run` issues git plumbing (fetch/worktree add/reset, base-freshness
    probes); `.run_streaming` launches the go-task target itself so its
    output can be drained incrementally. Same shapes as the real
    `ShellRunner` — tests inject a fake implementing just this surface."""

    def run(self, command: str, cwd: Path, env: dict[str, str] | None = None): ...

    def run_streaming(self, command: str, cwd: Path, env: dict[str, str] | None = None): ...

    def build_command(self, command: str, env_runner: str | None = None) -> str: ...


@dataclass
class RemoteExecDeps:
    """Collaborators `run_verb_stream` needs, injected so tests can fake
    them without touching a real filesystem/subprocess/git checkout.

    `config` is THIS machine's own `WorkspaceConfig` (its own repo paths —
    which generally differ from the operator's machine's paths, hence this
    can't be sent over the wire and must be resolved locally). `shell` does
    double duty for git commands and the streamed task run (see
    `ShellLike`). `workspace_root` anchors where remote worktrees live:
    `<workspace_root>/.worktrees/<task>/<repo>`, mirroring the local
    `WorktreeManager` hub layout.
    """

    config: WorkspaceConfig
    shell: ShellLike
    workspace_root: Path


def _hub_dir(workspace_root: Path, task: str) -> Path:
    return workspace_root / ".worktrees" / task


def _git_rev(shell: ShellLike, cwd: Path, ref: str) -> str | None:
    result = shell.run(f"git rev-parse {ref}", cwd=cwd)
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def check_base_freshness(
    shell: ShellLike, repo_path: Path, base_branch: str | None
) -> str | None:
    """MOS-203: before materializing, make sure this repo's knowledge of the
    task's base branch is current — auto-fetch it and, if origin had moved,
    return a warning line (str, no trailing newline) to surface into the
    stream. A remote run that silently sat on a stale base would build old
    code with no visible signal, hence the fold-in.

    Returns None when there's no base_branch to check, or when the fetch
    didn't move anything (already current) — a warning is only emitted when
    origin genuinely had new commits we didn't have yet.
    """
    if not base_branch:
        return None
    before = _git_rev(shell, repo_path, f"origin/{base_branch}")
    shell.run(f"git fetch origin {base_branch}", cwd=repo_path)
    after = _git_rev(shell, repo_path, f"origin/{base_branch}")
    if before is not None and after is not None and before != after:
        return (
            f"warning: base '{base_branch}' was behind origin "
            f"({before[:7]} -> {after[:7]}) — auto-fetched before materializing."
        )
    return None


def _run_checked(shell: ShellLike, command: str, cwd: Path, *, repo_name: str) -> None:
    """Run a git plumbing command that MUST succeed for the branch worktree
    to be usable. Raises `MaterializeError` (naming the repo, the failing
    command, and its stderr) on a non-zero exit rather than letting
    `run_verb_stream` continue on to run the task against a missing/stale
    worktree (Task 6 hardening — previously every `materialize_worktree`
    call site ignored `ShellResult.returncode` entirely)."""
    result = shell.run(command, cwd=cwd)
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        detail = f": {stderr}" if stderr else f" (exit {result.returncode})"
        raise MaterializeError(
            f"branch-materialize failed for repo {repo_name!r}: `{command}`{detail}"
        )


def materialize_worktree(
    shell: ShellLike, repo_path: Path, worktree_path: Path, branch: str, *, repo_name: str
) -> None:
    """Ensure `worktree_path` is a git worktree of `repo_path` sitting on
    `branch`, fresh from origin.

    `branch` already exists on origin (created by `mship spawn`/dispatch on
    the operator's machine and pushed there) — this NEVER creates a new
    branch here, it only fetches + tracks the existing one. Idempotent: a
    worktree that already exists is fetched + hard-reset to the new tip
    rather than re-added (the remote branch may have moved since the last
    remote run); a first-time run creates it with `git worktree add -B`,
    which is safe to re-run even if a stale local branch ref of the same
    name exists (e.g. left over from a removed worktree).

    Every git command runs through `_run_checked` (`repo_name` is only used
    for that error message): a failure here (e.g. the branch not yet pushed,
    a dirty/locked worktree) raises `MaterializeError` instead of silently
    letting execution continue against a missing/stale checkout.
    """
    _run_checked(shell, f"git fetch origin {branch}", repo_path, repo_name=repo_name)
    if (worktree_path / ".git").exists():
        _run_checked(shell, f"git fetch origin {branch}", worktree_path, repo_name=repo_name)
        _run_checked(shell, f"git checkout {branch}", worktree_path, repo_name=repo_name)
        _run_checked(shell, f"git reset --hard origin/{branch}", worktree_path, repo_name=repo_name)
    else:
        worktree_path.parent.mkdir(parents=True, exist_ok=True)
        _run_checked(
            shell,
            f"git worktree add -B {branch} {worktree_path} origin/{branch}",
            repo_path,
            repo_name=repo_name,
        )


def _drain_to_queue(proc, q: "queue.Queue[str]") -> list[threading.Thread]:
    """Start daemon threads that read `proc.stdout`/`proc.stderr` line by
    line and push each line onto `q` as it's produced — the same drain
    pattern as `util.stream_printer.drain_to_printer`, but feeding a queue
    a generator can pull from instead of a printer."""

    def _drain(stream):
        if stream is None:
            return
        try:
            while True:
                line = stream.readline()
                if not isinstance(line, str) or line == "":
                    break
                q.put(line)
        except Exception:
            pass
        finally:
            try:
                stream.close()
            except Exception:
                pass

    threads = [
        threading.Thread(target=_drain, args=(proc.stdout,), daemon=True),
        threading.Thread(target=_drain, args=(proc.stderr,), daemon=True),
    ]
    for t in threads:
        t.start()
    return threads


def _stream_proc_lines(proc) -> Iterator[bytes]:
    """Yield each stdout/stderr line from `proc` as UTF-8 bytes AS IT'S
    PRODUCED (not buffered until the process exits) — this is what makes
    `run_verb_stream` a live stream rather than a final blob. Returns once
    both drain threads have hit EOF and the queue is empty."""
    q: "queue.Queue[str]" = queue.Queue()
    threads = _drain_to_queue(proc, q)
    while any(t.is_alive() for t in threads) or not q.empty():
        try:
            line = q.get(timeout=0.05)
        except queue.Empty:
            continue
        yield line.encode("utf-8", errors="replace")
    for t in threads:
        t.join(timeout=1.0)


def _terminate_proc(proc) -> None:
    """Best-effort stop a possibly-still-running task subprocess.

    Called from `run_verb_stream`'s per-repo `finally` so a client disconnect
    (a GeneratorExit raised at a `yield` while the task is mid-run) doesn't
    orphan the go-task process. A process that already exited (the normal path,
    after `proc.wait()`) short-circuits via `poll()` and is a no-op.

    `ShellRunner.run_streaming` launches the task in its own session
    (`start_new_session=True` on POSIX), so the process is its own group leader
    — signal the whole group (`killpg`) to also catch grandchildren. Falls back
    to `proc.terminate()` on Windows, when there's no real OS pid (a test fake),
    or when the group is already gone.
    """
    if proc is None:
        return
    poll = getattr(proc, "poll", None)
    try:
        if callable(poll) and poll() is not None:
            return  # already exited — nothing to signal
    except Exception:
        pass

    import os as _os
    import signal as _signal

    pid = getattr(proc, "pid", None)
    if _os.name != "nt" and isinstance(pid, int) and pid > 0 and hasattr(_os, "killpg"):
        try:
            _os.killpg(pid, _signal.SIGTERM)
            return
        except (ProcessLookupError, OSError):
            pass
    terminate = getattr(proc, "terminate", None)
    if callable(terminate):
        try:
            terminate()
        except Exception:
            pass


def _build_artifact_tar(artifacts: list[_cap.Artifact]) -> bytes:
    """Pack the discovered artifact files into an in-memory tar, each stored
    at its basename (e.g. `screen.png`, `layout.json`) rather than its full
    remote temp-dir path — that's all Task 5's client needs to know to
    reconstruct them under its own local capture directory."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w") as tar:
        for artifact in artifacts:
            tar.add(artifact.path, arcname=artifact.path.name)
    return buf.getvalue()


def run_verb_stream(
    verb: str,
    task: str,
    repos: list[str],
    platform: str | None,
    *,
    deps: RemoteExecDeps,
    kind: str = "all",
    nonce: str,
) -> Iterator[bytes]:
    """The serve-side body of `POST /exec/{verb}`.

    A plain sync generator — the FastAPI endpoint runs it off the event
    loop (e.g. via `starlette.concurrency.iterate_in_threadpool`) since it
    does blocking subprocess/git I/O. For each repo, in order:

      1. MOS-203 base-freshness check (auto-fetch + an optional warning
         line — see `check_base_freshness`).
      2. Materialize `<workspace_root>/.worktrees/<task>/<repo>` on the
         task's branch (see `materialize_worktree`). `git_root` (nested
         subdirectory) repos skip their own fetch/worktree-add and resolve
         to a path under their parent's worktree instead, mirroring
         `WorktreeManager.spawn`'s treatment of subdirectory services.
      3. Resolve the repo's go-task target for `verb` + its env_runner;
         for `verb == "capture"` build the same env-var contract as local
         capture (`MSHIP_CAPTURE_DIR` a fresh remote temp dir,
         `MSHIP_CAPTURE_KINDS`, `MSHIP_CAPTURE_PLATFORM`) — see
         `mship.core.capture.run_capture`.
      4. Run it via `ShellRunner.run_streaming`, yielding each stdout/stderr
         line as it's produced.
      4b. For `verb == "capture"` only: once that repo's task exits, if it
          succeeded and produced artifacts in `MSHIP_CAPTURE_DIR`
          (`capture.discover_artifacts`), yield them as a length-prefixed
          tar block (`ARTIFACT_MARKER` line + raw tar bytes — see module
          docstring). A capture that exits 0 with NO recognized artifact is
          turned into an error (an error line + a non-zero exit), matching
          local `capture.run_capture`'s hard-error contract. Either way the
          remote capture temp dir is removed afterward (even on a client
          disconnect — see the per-repo `finally`). `run`/`build` skip this
          entirely (stream-only).
      5. Stop at the first repo whose task exits non-zero (fail-fast,
         mirroring `RepoExecutor`'s tier behavior) rather than continuing
         to the next repo.

    Always ends with the trailing sentinel line
    `f"{EXIT_MARKER}:{nonce} {code}\\n"` conveying the run's exit code as
    DATA — never raises for a non-zero task exit (see module docstring for
    the full wire contract). `nonce` is the per-request anti-spoof secret
    (see `core/serve.py post_exec`); every control record is tagged with it.

    Task 6 hardening (both fail the SAME way — an error line naming the
    problem, then a non-zero `__MSHIP_EXIT__`, never a raised exception mid
    generator):
      - An unknown repo name (not in `deps.config.repos`) is rejected
        UPFRONT, before the per-repo loop starts and before any git/task
        command runs for ANY repo in the request (Task 3 previously left
        this a raw `KeyError` on `config.repos[repo_name]`).
      - A branch-materialize failure (a git fetch/checkout/reset/worktree-add
        exiting non-zero — see `materialize_worktree`/`MaterializeError`)
        stops at that repo exactly like a failing task would; already-yielded
        output from earlier repos in the same request is preserved.
    """
    if verb not in VERBS:
        raise UnknownVerbError(
            f"unknown verb {verb!r}; expected one of {VERBS}"
        )

    kinds: list[str] | None = None
    if verb == "capture":
        kinds = _cap.resolve_kinds(kind)

    config = deps.config
    shell = deps.shell
    hub = _hub_dir(deps.workspace_root, task)
    branch = config.branch_pattern.replace("{slug}", task)

    unknown_repos = [r for r in repos if r not in config.repos]
    if unknown_repos:
        yield (
            f"error: unknown repo(s) {', '.join(unknown_repos)}; known "
            f"repos: {', '.join(sorted(config.repos)) or '(none)'}\n"
        ).encode("utf-8")
        yield f"{EXIT_MARKER}:{nonce} 2\n".encode("utf-8")
        return

    materialized: dict[str, Path] = {}
    exit_code = 0

    def _ensure_materialized(top_repo: str) -> Iterator[bytes]:
        """Materialize a TOP-LEVEL repo's task-branch worktree at
        `<hub>/<repo>`, recording it in `materialized`. A generator so it can
        yield the base-freshness warning (see `check_base_freshness`) and, on
        failure, the error line + trailing exit sentinel straight into the
        stream. Its `yield from` value (PEP 380) is True on success, False if
        the materialize failed — in which case the exit sentinel has ALREADY
        been emitted and the caller MUST `return` to abort the whole request.

        Idempotent: a repo already in `materialized` (e.g. a parent brought in
        while resolving an earlier `git_root` child, then reached again in the
        loop, or a parent also listed explicitly in `repos`) is a no-op — it is
        never re-fetched/reset."""
        if top_repo in materialized:
            return True
        rc = config.repos[top_repo]
        repo_path = rc.path
        worktree_path = hub / top_repo

        warning = check_base_freshness(shell, repo_path, rc.base_branch)
        if warning is not None:
            yield f"{warning}\n".encode("utf-8")

        try:
            materialize_worktree(shell, repo_path, worktree_path, branch, repo_name=top_repo)
        except MaterializeError as exc:
            yield f"error: {exc}\n".encode("utf-8")
            yield f"{EXIT_MARKER}:{nonce} 1\n".encode("utf-8")
            return False

        materialized[top_repo] = worktree_path
        return True

    for repo_name in repos:
        repo_config = config.repos[repo_name]

        if repo_config.git_root is not None:
            # Subdirectory child (mirrors WorktreeManager.spawn): its git tree
            # IS the parent's worktree. Guarantee the PARENT is materialized
            # first (parent-first) — even when this request lists only the
            # child, or lists it before its parent — then resolve the child's
            # path UNDER the materialized parent worktree. Previously this fell
            # back to a never-fetched `hub / git_root` dir, so the task could
            # run against the serve host's stale/source tree.
            if not (yield from _ensure_materialized(repo_config.git_root)):
                return
            parent_wt = materialized[repo_config.git_root]
            worktree_path = parent_wt / repo_config.path
            materialized[repo_name] = worktree_path
        else:
            if not (yield from _ensure_materialized(repo_name)):
                return
            worktree_path = materialized[repo_name]

        actual_task_name = repo_config.tasks.get(verb, verb)
        env_runner = repo_config.env_runner or config.env_runner

        # `out_dir`/`proc` live outside the try so the `finally` can always
        # clean them up even if a client disconnect (GeneratorExit) fires at
        # any `yield` below — before the temp dir would otherwise be removed,
        # and while the task subprocess is still running (FIX 8).
        out_dir: Path | None = None
        proc = None
        try:
            env: dict[str, str] | None = None
            if verb == "capture":
                out_dir = Path(tempfile.mkdtemp(prefix="mship-remote-capture-"))
                env = {
                    "MSHIP_CAPTURE_DIR": str(out_dir),
                    "MSHIP_CAPTURE_KINDS": ",".join(kinds or []),
                }
                if platform is not None:
                    env["MSHIP_CAPTURE_PLATFORM"] = platform

            command = shell.build_command(f"task {actual_task_name}", env_runner)
            proc = shell.run_streaming(command, cwd=worktree_path, env=env)
            yield from _stream_proc_lines(proc)
            exit_code = proc.wait()

            if verb == "capture":
                artifacts = _cap.discover_artifacts(out_dir, kinds or []) if exit_code == 0 else []
                if artifacts:
                    tar_bytes = _build_artifact_tar(artifacts)
                    yield f"{ARTIFACT_MARKER}:{nonce} {len(tar_bytes)}\n".encode("utf-8")
                    yield tar_bytes
                elif exit_code == 0:
                    # Parity with local `capture.run_capture`: a capture that
                    # "succeeds" but produced nothing recognized is a hard
                    # error, not a silent success.
                    yield (
                        f"error: capture target produced no recognized artifact "
                        f"in {out_dir} for kinds {kinds or []}.\n"
                    ).encode("utf-8")
                    exit_code = 1
        finally:
            _terminate_proc(proc)
            if out_dir is not None:
                shutil.rmtree(out_dir, ignore_errors=True)

        if exit_code != 0:
            break

    yield f"{EXIT_MARKER}:{nonce} {exit_code}\n".encode("utf-8")
