"""Serve-side execution of a go-task verb on THIS machine — the "remote" side
of `mship run/capture/build --remote[=role]` (see
specs/2026-07-11-remote-run-machine.md, MOS-191/MOS-203).

The client (a different mship workspace, Task 5) POSTs `{task, repos,
platform?, kind?}` to `POST /exec/{verb}` (registered in `core/serve.py`,
inheriting serve's bearer-auth dependency). This module is the generator
`run_verb_stream` that endpoint drives: it materializes the task's branch
worktree on this machine (the branch already exists on origin — pushed by
the operator's `mship spawn`/dispatch — this never creates a new branch),
runs the repo's go-task target with the same env-var contract as a local
run, and yields the subprocess's output incrementally so the client can
render it live.

Wire contract (Task 5's client parses this):
    - Every line yielded up to the last one is raw task output (stdout and
      stderr interleaved, one write per line, newline-terminated, UTF-8).
    - Any freeform notice lines (e.g. the MOS-203 base-freshness warning)
      are indistinguishable from task output on the wire — they're just
      more lines — so a client that renders every line live is correct by
      construction; nothing needs it to distinguish notice vs. task output.
    - CONTROL RECORDS are anti-spoof-tagged with a PER-REQUEST NONCE the
      task cannot predict (generated by `core/serve.py post_exec`, handed
      to the client out-of-band as the `X-Mship-Exec-Nonce` response header
      — sent before the streamed body, so the task can never inject it).
      Without the nonce tag a control line is just ordinary task output:
      a remote branch that prints a bare `__MSHIP_EXIT__ 0` can NOT
      green-wash a failed build.
    - For `verb == "capture"` ONLY, if the task exits 0 and produces at
      least one artifact (`capture.discover_artifacts` on the remote's
      `MSHIP_CAPTURE_DIR`), a length-prefixed tar block is emitted after
      that repo's task lines and before the exit sentinel:
          __MSHIP_ARTIFACTS__:<nonce> <byte_count>\\n
          <exactly byte_count bytes of UNCOMPRESSED tar, containing the
           discovered artifact files at their basenames, e.g. screen.png,
           layout.json>
      `<byte_count>` is a base-10 int. The client must read exactly that
      many raw bytes as the tar (binary-safe — do NOT line-split them)
      before resuming line-based reads. No block is emitted when capture
      produced no artifacts; instead a capture that exits 0 with NO
      recognized artifact is turned into an ERROR (an error line + a
      non-zero exit code), matching local `capture.run_capture`. `run`/
      `build` never emit an artifact block.
    - The LAST line always matches `__MSHIP_EXIT__:<nonce> <code>\\n` where
      <code> is a base-10 int (0 == success). This conveys the remote
      task's exit code as DATA, never as an HTTP error status — a non-zero
      task exit does not raise; the client must parse this trailing line
      (matched against its nonce) to learn the real result and mirror it as
      its own process exit code.
"""
from __future__ import annotations

import errno
import fcntl
import hashlib
import io
import queue
import shlex
import shutil
import tarfile
import tempfile
import threading
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, Protocol

from mship.core import capture as _cap
from mship.core import remote_setup
from mship.core.config import WorkspaceConfig
from mship.core.run_ref import RunRefNameError
from mship.core.run_ref import run_ref as build_run_ref
from mship.util.shell import ShellCancelled, _terminate_owned_process_group
from mship.util.taskfile import taskfile_has_target

VERBS: tuple[str, ...] = ("run", "capture", "build")

# Trailing sentinel line: `f"{EXIT_MARKER}:{nonce} {code}\n"` — the `:{nonce}`
# tag (a per-request secret handed to the client via the X-Mship-Exec-Nonce
# response header) is what stops task stdout from spoofing the exit code. See
# the module docstring for the full wire contract Task 5's client must parse.
EXIT_MARKER = "__MSHIP_EXIT__"

# Length-prefixed tar block marker (capture only):
# `f"{ARTIFACT_MARKER}:{nonce} {len(tar_bytes)}\n"` immediately followed by
# exactly that many raw (uncompressed) tar bytes. Nonce-tagged for the same
# anti-spoof reason as EXIT_MARKER. See module docstring for the full framing.
ARTIFACT_MARKER = "__MSHIP_ARTIFACTS__"


class UnknownVerbError(ValueError):
    """`verb` is not one of `VERBS`."""


class MaterializeError(Exception):
    """A git plumbing command needed to bring a repo's task-branch worktree
    up to date (fetch, checkout, reset, or worktree add) exited non-zero.

    Raised by `materialize_worktree`/`_run_checked` and caught by
    `run_verb_stream`, which turns it into a clean stream error (an error
    line naming the repo + failing command, then a non-zero `__MSHIP_EXIT__`)
    rather than silently running the task against a missing/stale worktree
    (Task 6 hardening — see the module docstring's wire contract)."""


class ShellLike(Protocol):
    """The subset of `mship.util.shell.ShellRunner` this module needs.
    `.run_argv` issues git plumbing (fetch/worktree add/reset, base-freshness
    probes); `.run_streaming` launches the go-task target itself so its
    output can be drained incrementally. Same shapes as the real
    `ShellRunner` — tests inject a fake implementing just this surface."""

    def run_argv(
        self,
        args: Sequence[str],
        cwd: Path,
        env: dict[str, str] | None = None,
        *,
        cancel_event: threading.Event | None = None,
    ): ...

    def run_streaming(self, command: str, cwd: Path, env: dict[str, str] | None = None): ...

    def build_command(self, command: str, env_runner: str | None = None) -> str: ...


@dataclass
class RemoteExecDeps:
    """Collaborators `run_verb_stream` needs, injected so tests can fake
    them without touching a real filesystem/subprocess/git checkout.

    `config` is THIS machine's own `WorkspaceConfig` (its own repo paths —
    which generally differ from the operator's machine's paths, hence this
    can't be sent over the wire and must be resolved locally). `shell` does
    double duty for git commands and the streamed task run (see
    `ShellLike`). `workspace_root` anchors where remote worktrees live:
    `<workspace_root>/.worktrees/<task>/<repo>`, mirroring the local
    `WorktreeManager` hub layout. `cancel_event` lets the HTTP response stop a
    quiet subprocess promptly when its client disconnects.
    """

    config: WorkspaceConfig
    shell: ShellLike
    workspace_root: Path
    cancel_event: threading.Event | None = None


def _hub_dir(workspace_root: Path, task: str) -> Path:
    return workspace_root / ".worktrees" / task


def _acquire_task_execution_lock(
    workspace_root: Path,
    task: str,
) -> io.TextIOWrapper:
    lock_dir = workspace_root / ".mothership" / "remote-exec-locks"
    lock_dir.mkdir(parents=True, exist_ok=True)
    digest = hashlib.sha256(task.encode("utf-8")).hexdigest()
    lock_file = (lock_dir / f"{digest}.lock").open("a+")
    try:
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError as exc:
        lock_file.close()
        if exc.errno in {errno.EACCES, errno.EAGAIN, errno.EWOULDBLOCK}:
            raise BlockingIOError(exc.errno, exc.strerror) from exc
        raise
    except BaseException:
        lock_file.close()
        raise
    return lock_file


def _run_shell(
    shell: ShellLike,
    args: Sequence[str],
    cwd: Path,
    *,
    cancel_event: threading.Event | None,
):
    return shell.run_argv(
        args,
        cwd=cwd,
        cancel_event=cancel_event,
    )


def _git_rev(
    shell: ShellLike,
    cwd: Path,
    ref: str,
    *,
    cancel_event: threading.Event | None = None,
) -> str | None:
    result = _run_shell(
        shell,
        ["git", "rev-parse", ref],
        cwd,
        cancel_event=cancel_event,
    )
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def check_base_freshness(
    shell: ShellLike,
    repo_path: Path,
    base_branch: str | None,
    *,
    cancel_event: threading.Event | None = None,
) -> str | None:
    """MOS-203: before materializing, make sure this repo's knowledge of the
    task's base branch is current — auto-fetch it and, if origin had moved,
    return a warning line (str, no trailing newline) to surface into the
    stream. A remote run that silently sat on a stale base would build old
    code with no visible signal, hence the fold-in.

    Returns None when there's no base_branch to check, or when the fetch
    didn't move anything (already current) — a warning is only emitted when
    origin genuinely had new commits we didn't have yet.
    """
    if not base_branch:
        return None
    before = _git_rev(
        shell,
        repo_path,
        f"origin/{base_branch}",
        cancel_event=cancel_event,
    )
    _run_shell(
        shell,
        ["git", "fetch", "origin", base_branch],
        repo_path,
        cancel_event=cancel_event,
    )
    after = _git_rev(
        shell,
        repo_path,
        f"origin/{base_branch}",
        cancel_event=cancel_event,
    )
    if before is not None and after is not None and before != after:
        return (
            f"warning: base '{base_branch}' was behind origin "
            f"({before[:7]} -> {after[:7]}) — auto-fetched before materializing."
        )
    return None


def _run_checked(
    shell: ShellLike,
    args: Sequence[str],
    cwd: Path,
    *,
    repo_name: str,
    cancel_event: threading.Event | None = None,
) -> None:
    """Run a git plumbing command that MUST succeed for the branch worktree
    to be usable. Raises `MaterializeError` (naming the repo, the failing
    command, and its stderr) on a non-zero exit rather than letting
    `run_verb_stream` continue on to run the task against a missing/stale
    worktree (Task 6 hardening — previously every `materialize_worktree`
    call site ignored `ShellResult.returncode` entirely)."""
    result = _run_shell(
        shell,
        args,
        cwd,
        cancel_event=cancel_event,
    )
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        detail = f": {stderr}" if stderr else f" (exit {result.returncode})"
        command = shlex.join(args)
        raise MaterializeError(
            f"branch-materialize failed for repo {repo_name!r}: `{command}`{detail}"
        )


def materialize_worktree(
    shell: ShellLike,
    repo_path: Path,
    worktree_path: Path,
    branch: str,
    *,
    repo_name: str,
    run_ref: str | None = None,
    cancel_event: threading.Event | None = None,
) -> None:
    """Ensure `worktree_path` is a git worktree of `repo_path` holding the
    revision this run is supposed to execute.

    Two modes.

    `run_ref` GIVEN (spec remote-exact-copy): the operator pushed a commit
    synthesized from their working tree straight to this host, so the revision is
    ALREADY in this repository. Materialization is a reset to a LOCAL ref with NO
    FETCH — origin is not consulted at all, which is also why the caller skips
    the base-freshness probe for these repos. HEAD is left DETACHED on purpose:
    the scratch commit is throwaway state, and pointing a branch at it would
    dress it up as history. `git clean -fd` removes leftovers from a previous
    run so the result is an exact copy; it does not remove gitignored files, so
    dependencies derived by `task setup` survive between runs.

    `run_ref` NONE (unchanged from before): `branch` already exists on origin
    (created by `mship spawn`/dispatch on the operator's machine and pushed
    there) — this NEVER creates a new branch here, it only fetches + tracks the
    existing one. Idempotent: an existing worktree is fetched + hard-reset to the
    new tip; a first-time run creates it with `git worktree add -B`, which is
    safe to re-run even if a stale local branch ref of the same name exists.

    Every git command runs through `_run_checked` (`repo_name` is only used for
    that error message): a failure here raises `MaterializeError` instead of
    silently letting execution continue against a missing/stale checkout.
    """
    if run_ref is not None:
        if (worktree_path / ".git").exists():
            # `checkout --detach` with NO ref keeps the current commit, so it
            # succeeds even when the worktree is dirty from the last run
            # (verified); the reset then moves detached HEAD without ever moving
            # a branch.
            _run_checked(
                shell,
                ["git", "checkout", "--detach"],
                worktree_path,
                repo_name=repo_name,
                cancel_event=cancel_event,
            )
            _run_checked(
                shell,
                ["git", "reset", "--hard", run_ref],
                worktree_path,
                repo_name=repo_name,
                cancel_event=cancel_event,
            )
            _run_checked(
                shell,
                ["git", "clean", "-fd"],
                worktree_path,
                repo_name=repo_name,
                cancel_event=cancel_event,
            )
        else:
            worktree_path.parent.mkdir(parents=True, exist_ok=True)
            _run_checked(
                shell,
                [
                    "git",
                    "worktree",
                    "add",
                    "--detach",
                    str(worktree_path),
                    run_ref,
                ],
                repo_path,
                repo_name=repo_name,
                cancel_event=cancel_event,
            )
        return

    _run_checked(
        shell,
        ["git", "fetch", "origin", branch],
        repo_path,
        repo_name=repo_name,
        cancel_event=cancel_event,
    )
    if (worktree_path / ".git").exists():
        _run_checked(
            shell,
            ["git", "fetch", "origin", branch],
            worktree_path,
            repo_name=repo_name,
            cancel_event=cancel_event,
        )
        _run_checked(
            shell,
            ["git", "checkout", branch],
            worktree_path,
            repo_name=repo_name,
            cancel_event=cancel_event,
        )
        _run_checked(
            shell,
            ["git", "reset", "--hard", f"origin/{branch}"],
            worktree_path,
            repo_name=repo_name,
            cancel_event=cancel_event,
        )
    else:
        worktree_path.parent.mkdir(parents=True, exist_ok=True)
        _run_checked(
            shell,
            [
                "git",
                "worktree",
                "add",
                "-B",
                branch,
                str(worktree_path),
                f"origin/{branch}",
            ],
            repo_path,
            repo_name=repo_name,
            cancel_event=cancel_event,
        )


def _drain_to_queue(proc, q: "queue.Queue[str]") -> list[threading.Thread]:
    """Start daemon threads that read `proc.stdout`/`proc.stderr` line by
    line and push each line onto `q` as it's produced — the same drain
    pattern as `util.stream_printer.drain_to_printer`, but feeding a queue
    a generator can pull from instead of a printer."""

    def _drain(stream):
        if stream is None:
            return
        try:
            while True:
                line = stream.readline()
                if not isinstance(line, str) or line == "":
                    break
                q.put(line)
        except Exception:
            pass
        finally:
            try:
                stream.close()
            except Exception:
                pass

    threads = [
        threading.Thread(target=_drain, args=(proc.stdout,), daemon=True),
        threading.Thread(target=_drain, args=(proc.stderr,), daemon=True),
    ]
    for t in threads:
        t.start()
    return threads


def _stream_proc_lines(
    proc,
    cancel_event: threading.Event | None = None,
) -> Iterator[bytes]:
    """Yield each stdout/stderr line from `proc` as UTF-8 bytes AS IT'S
    PRODUCED (not buffered until the process exits) — this is what makes
    `run_verb_stream` a live stream rather than a final blob. Returns once
    both pipes are drained and the process has exited, or returns False when
    the response reports that its client disconnected."""
    q: "queue.Queue[str]" = queue.Queue()
    threads = _drain_to_queue(proc, q)
    poll = getattr(proc, "poll", None)

    def process_is_running() -> bool:
        if not callable(poll):
            return False
        try:
            return poll() is None
        except Exception:
            return False

    while (
        any(t.is_alive() for t in threads)
        or not q.empty()
        or process_is_running()
    ):
        if cancel_event is not None and cancel_event.is_set():
            return False
        try:
            line = q.get(timeout=0.05)
        except queue.Empty:
            continue
        yield line.encode("utf-8", errors="replace")
    for t in threads:
        t.join(timeout=1.0)
    return True


def _terminate_proc(proc, *, completed: bool) -> None:
    """Stop abnormal task trees; leave normally reaped groups untouched."""
    if proc is None or completed:
        return

    try:
        _terminate_owned_process_group(proc)
    except Exception:
        # Preserve cleanup for lightweight Popen-shaped fakes that do not expose
        # the full process-group surface.
        terminate = getattr(proc, "terminate", None)
        if not callable(terminate):
            return
        try:
            terminate()
        except Exception:
            return
    wait = getattr(proc, "wait", None)
    if not callable(wait):
        return
    try:
        wait()
    except Exception:
        pass


def _build_artifact_tar(artifacts: list[_cap.Artifact]) -> bytes:
    """Pack the discovered artifact files into an in-memory tar, each stored
    at its basename (e.g. `screen.png`, `layout.json`) rather than its full
    remote temp-dir path — that's all Task 5's client needs to know to
    reconstruct them under its own local capture directory."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w") as tar:
        for artifact in artifacts:
            tar.add(artifact.path, arcname=artifact.path.name)
    return buf.getvalue()


def run_verb_stream(
    verb: str,
    task: str,
    repos: list[str],
    platform: str | None,
    *,
    deps: RemoteExecDeps,
    kind: str = "all",
    nonce: str,
    run_ref_repos: list[str] | None = None,
) -> Iterator[bytes]:
    """Run one remote execution stream while owning its per-task process lock."""
    try:
        lock_file = _acquire_task_execution_lock(deps.workspace_root, task)
    except BlockingIOError:
        yield (
            f"error: remote task {task!r} is already running; "
            "try again after it finishes\n"
        ).encode("utf-8")
        yield f"{EXIT_MARKER}:{nonce} 2\n".encode("utf-8")
        return
    except (OSError, UnicodeError):
        yield b"error: remote-task locking failed; execution was not started\n"
        yield f"{EXIT_MARKER}:{nonce} 1\n".encode("utf-8")
        return

    try:
        yield from _run_verb_stream_unlocked(
            verb,
            task,
            repos,
            platform,
            deps=deps,
            kind=kind,
            nonce=nonce,
            run_ref_repos=run_ref_repos,
        )
    finally:
        try:
            fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)
        finally:
            lock_file.close()


def _run_verb_stream_unlocked(
    verb: str,
    task: str,
    repos: list[str],
    platform: str | None,
    *,
    deps: RemoteExecDeps,
    kind: str = "all",
    nonce: str,
    run_ref_repos: list[str] | None = None,
) -> Iterator[bytes]:
    """The serve-side body of `POST /exec/{verb}`.

    A plain sync generator — the FastAPI endpoint runs it off the event
    loop (e.g. via `starlette.concurrency.iterate_in_threadpool`) since it
    does blocking subprocess/git I/O. For each repo, in order:

      1. MOS-203 base-freshness check (auto-fetch + an optional warning
         line — see `check_base_freshness`).
      2. Materialize `<workspace_root>/.worktrees/<task>/<repo>` on the
         task's branch (see `materialize_worktree`). `git_root` (nested
         subdirectory) repos skip their own fetch/worktree-add and resolve
         to a path under their parent's worktree instead, mirroring
         `WorktreeManager.spawn`'s treatment of subdirectory services.
      2b. A repo named in `run_ref_repos` is materialized from THIS host's own
          scratch ref for the task instead — the operator pushed a commit
          synthesized from their working tree straight here, so the revision is
          already local and NO fetch (not even the base-freshness probe, which
          exists only to refresh this host's view of origin) is issued for it.
          Names are TOP-LEVEL git repo names, so a `git_root` child is covered
          by its parent's entry.
      3. Resolve the repo's go-task target for `verb` + its env_runner;
         for `verb == "capture"` build the same env-var contract as local
         capture (`MSHIP_CAPTURE_DIR` a fresh remote temp dir,
         `MSHIP_CAPTURE_KINDS`, `MSHIP_CAPTURE_PLATFORM`) — see
         `mship.core.capture.run_capture`.
      4. Run it via `ShellRunner.run_streaming`, yielding each stdout/stderr
         line as it's produced.
      4b. For `verb == "capture"` only: once that repo's task exits, if it
          succeeded and produced artifacts in `MSHIP_CAPTURE_DIR`
          (`capture.discover_artifacts`), yield them as a length-prefixed
          tar block (`ARTIFACT_MARKER` line + raw tar bytes — see module
          docstring). A capture that exits 0 with NO recognized artifact is
          turned into an error (an error line + a non-zero exit), matching
          local `capture.run_capture`'s hard-error contract. Either way the
          remote capture temp dir is removed afterward (even on a client
          disconnect — see the per-repo `finally`). `run`/`build` skip this
          entirely (stream-only).
      5. Stop at the first repo whose task exits non-zero (fail-fast,
         mirroring `RepoExecutor`'s tier behavior) rather than continuing
         to the next repo.

    Always ends with the trailing sentinel line
    `f"{EXIT_MARKER}:{nonce} {code}\\n"` conveying the run's exit code as
    DATA — never raises for a non-zero task exit (see module docstring for
    the full wire contract). `nonce` is the per-request anti-spoof secret
    (see `core/serve.py post_exec`); every control record is tagged with it.

    Task 6 hardening (both fail the SAME way — an error line naming the
    problem, then a non-zero `__MSHIP_EXIT__`, never a raised exception mid
    generator):
      - An unknown repo name (not in `deps.config.repos`) is rejected
        UPFRONT, before the per-repo loop starts and before any git/task
        command runs for ANY repo in the request (Task 3 previously left
        this a raw `KeyError` on `config.repos[repo_name]`).
      - A branch-materialize failure (a git fetch/checkout/reset/worktree-add
        exiting non-zero — see `materialize_worktree`/`MaterializeError`)
        stops at that repo exactly like a failing task would; already-yielded
        output from earlier repos in the same request is preserved.
    """
    if verb not in VERBS:
        raise UnknownVerbError(
            f"unknown verb {verb!r}; expected one of {VERBS}"
        )

    kinds: list[str] | None = None
    if verb == "capture":
        kinds = _cap.resolve_kinds(kind)

    config = deps.config
    shell = deps.shell
    hub = _hub_dir(deps.workspace_root, task)
    branch = config.branch_pattern.replace("{slug}", task)

    unknown_repos = [r for r in repos if r not in config.repos]
    if unknown_repos:
        yield (
            f"error: unknown repo(s) {', '.join(unknown_repos)}; known "
            f"repos: {', '.join(sorted(config.repos)) or '(none)'}\n"
        ).encode("utf-8")
        yield f"{EXIT_MARKER}:{nonce} 2\n".encode("utf-8")
        return

    scratch_repos = sorted(set(run_ref_repos or []))
    run_refs: dict[str, str] = {}
    for scratch_repo in scratch_repos:
        try:
            run_refs[scratch_repo] = build_run_ref(task, scratch_repo)
        except RunRefNameError as exc:
            # The ref is interpolated into git commands run with shell=True, so
            # a name that cannot form one is refused before anything runs — as
            # stream DATA, never a raised exception mid-generator, matching the
            # unknown-repo guard above.
            yield f"error: cannot build a run ref for this request: {exc}\n".encode("utf-8")
            yield f"{EXIT_MARKER}:{nonce} 2\n".encode("utf-8")
            return

    materialized: dict[str, Path] = {}
    exit_code = 0

    def _ensure_materialized(top_repo: str) -> Iterator[bytes]:
        """Materialize a TOP-LEVEL repo's task-branch worktree at
        `<hub>/<repo>`, recording it in `materialized`. A generator so it can
        yield the base-freshness warning or a clean materialization error through
        the stream. Its `yield from` value (PEP 380) is True on success, False
        if materialization fails or the client disconnects. A materialization
        failure has already emitted its exit sentinel; cancellation simply
        unwinds so the response can close.

        Idempotent: a repo already in `materialized` (e.g. a parent brought in
        while resolving an earlier `git_root` child, then reached again in the
        loop, or a parent also listed explicitly in `repos`) is a no-op — it is
        never re-fetched/reset."""
        if top_repo in materialized:
            return True
        rc = config.repos[top_repo]
        repo_path = rc.path
        worktree_path = hub / top_repo
        ref = run_refs.get(top_repo)

        try:
            if ref is None:
                # Origin is the source of truth for this repo, so make sure this
                # host's view of its base is current first (MOS-203). Skipped
                # entirely on the scratch-ref path: nothing there comes from
                # origin, and a fetch would be pure latency.
                warning = check_base_freshness(
                    shell,
                    repo_path,
                    rc.base_branch,
                    cancel_event=deps.cancel_event,
                )
                if warning is not None:
                    yield f"{warning}\n".encode("utf-8")

            materialize_worktree(
                shell,
                repo_path,
                worktree_path,
                branch,
                repo_name=top_repo,
                run_ref=ref,
                cancel_event=deps.cancel_event,
            )
        except ShellCancelled:
            return False
        except MaterializeError as exc:
            yield f"error: {exc}\n".encode("utf-8")
            yield f"{EXIT_MARKER}:{nonce} 1\n".encode("utf-8")
            return False

        materialized[top_repo] = worktree_path
        return True

    def _ensure_setup(repo_name: str, repo_config, worktree_path: Path) -> Iterator[bytes]:
        """Run `task setup` in a freshly-materialized worktree when it is
        needed, streaming its output live exactly like the verb itself.

        Git carries source, not dependencies. Without this, an exact-source run
        against stale dependencies fails with a module-not-found that has no
        visible relationship to the edit — the same confusing-staleness class
        the rest of this feature exists to eliminate. So the host DERIVES them.

        Keyed (see `core/remote_setup.py`): the first materialization on this
        host, then only when the repo's declared `setup_inputs` change. Skipped
        entirely for a repo that declares `setup` not applicable or whose
        Taskfile has no such target — `task setup` in a repo that never defined
        one exits non-zero, and that must not fail every remote run.

        PEP 380 value: True to continue, False when setup FAILED — in which case
        the error line and the exit sentinel have ALREADY been emitted and the
        caller MUST return, exactly like `_ensure_materialized`.
        """
        if "setup" in repo_config.not_applicable:
            return True
        actual_setup = repo_config.tasks.get("setup", "setup")
        if not taskfile_has_target(worktree_path, actual_setup):
            return True

        key = remote_setup.setup_key(worktree_path, repo_config.setup_inputs)
        key_path = remote_setup.key_file(deps.workspace_root, task, repo_name)
        if not remote_setup.needs_setup(key_path, key):
            return True

        yield f"setup: {repo_name} (task {actual_setup})\n".encode("utf-8")
        env_runner = repo_config.env_runner or config.env_runner
        command = shell.build_command(f"task {actual_setup}", env_runner)
        completed = False
        proc = None
        try:
            proc = shell.run_streaming(command, cwd=worktree_path, env=None)
            if not (yield from _stream_proc_lines(proc, deps.cancel_event)):
                return False
            setup_code = proc.wait()
            completed = True
        finally:
            _terminate_proc(proc, completed=completed)

        if setup_code != 0:
            # Surface setup's OWN failure rather than letting the verb run
            # against half-built dependencies and report something that does not
            # name the real cause (spec ac18).
            yield (
                f"error: `task {actual_setup}` failed on the run host for repo "
                f"{repo_name!r} (exit {setup_code}); the output above is setup's "
                f"own. The {verb} was not started.\n"
            ).encode("utf-8")
            yield f"{EXIT_MARKER}:{nonce} {setup_code}\n".encode("utf-8")
            return False

        # Recorded only after a SUCCESSFUL setup: caching a failure would skip
        # the retry that fixes it.
        remote_setup.record_setup(key_path, key)
        return True

    for repo_name in repos:
        repo_config = config.repos[repo_name]

        if repo_config.git_root is not None:
            # Subdirectory child (mirrors WorktreeManager.spawn): its git tree
            # IS the parent's worktree. Guarantee the PARENT is materialized
            # first (parent-first) — even when this request lists only the
            # child, or lists it before its parent — then resolve the child's
            # path UNDER the materialized parent worktree. Previously this fell
            # back to a never-fetched `hub / git_root` dir, so the task could
            # run against the serve host's stale/source tree.
            if not (yield from _ensure_materialized(repo_config.git_root)):
                return
            parent_wt = materialized[repo_config.git_root]
            worktree_path = parent_wt / repo_config.path
            materialized[repo_name] = worktree_path
        else:
            if not (yield from _ensure_materialized(repo_name)):
                return
            worktree_path = materialized[repo_name]

        if not (yield from _ensure_setup(repo_name, repo_config, worktree_path)):
            return

        actual_task_name = repo_config.tasks.get(verb, verb)
        env_runner = repo_config.env_runner or config.env_runner

        # `out_dir`/`proc` live outside the try so the `finally` can always
        # clean them up even if a client disconnect (GeneratorExit) fires at
        # any `yield` below — before the temp dir would otherwise be removed,
        # and while the task subprocess is still running (FIX 8).
        out_dir: Path | None = None
        proc = None
        completed = False
        try:
            env: dict[str, str] | None = None
            if verb == "capture":
                out_dir = Path(tempfile.mkdtemp(prefix="mship-remote-capture-"))
                env = {
                    "MSHIP_CAPTURE_DIR": str(out_dir),
                    "MSHIP_CAPTURE_KINDS": ",".join(kinds or []),
                }
                if platform is not None:
                    env["MSHIP_CAPTURE_PLATFORM"] = platform

            command = shell.build_command(f"task {actual_task_name}", env_runner)
            proc = shell.run_streaming(command, cwd=worktree_path, env=env)
            if not (yield from _stream_proc_lines(proc, deps.cancel_event)):
                return
            exit_code = proc.wait()
            completed = True

            if verb == "capture":
                artifacts = _cap.discover_artifacts(out_dir, kinds or []) if exit_code == 0 else []
                if artifacts:
                    tar_bytes = _build_artifact_tar(artifacts)
                    yield f"{ARTIFACT_MARKER}:{nonce} {len(tar_bytes)}\n".encode("utf-8")
                    yield tar_bytes
                elif exit_code == 0:
                    # Parity with local `capture.run_capture`: a capture that
                    # "succeeds" but produced nothing recognized is a hard
                    # error, not a silent success.
                    yield (
                        f"error: capture target produced no recognized artifact "
                        f"in {out_dir} for kinds {kinds or []}.\n"
                    ).encode("utf-8")
                    exit_code = 1
        finally:
            _terminate_proc(proc, completed=completed)
            if out_dir is not None:
                shutil.rmtree(out_dir, ignore_errors=True)

        if exit_code != 0:
            break

    yield f"{EXIT_MARKER}:{nonce} {exit_code}\n".encode("utf-8")
