"""Serve-side execution of a go-task verb on THIS machine — the "remote" side
of `mship run/capture/build --remote[=role]` (see
specs/2026-07-11-remote-run-machine.md, MOS-191/MOS-203).

The client (a different mship workspace, Task 5) POSTs `{task, repos,
platform?, kind?}` to `POST /exec/{verb}` (registered in `core/serve.py`,
inheriting serve's bearer-auth dependency). This module is the generator
`run_verb_stream` that endpoint drives: it materializes the task's branch
worktree on this machine (the branch already exists on origin — pushed by
the operator's `mship spawn`/dispatch — this never creates a new branch),
runs the repo's go-task target with the same env-var contract as a local
run, and yields the subprocess's output incrementally so the client can
render it live.

Wire contract (Task 5's client parses this):
    - Every line yielded up to the last one is raw task output (stdout and
      stderr interleaved, one write per line, newline-terminated, UTF-8).
    - Any freeform notice lines (e.g. the MOS-203 base-freshness warning)
      are indistinguishable from task output on the wire — they're just
      more lines — so a client that renders every line live is correct by
      construction; nothing needs it to distinguish notice vs. task output.
    - CONTROL RECORDS are anti-spoof-tagged with a PER-REQUEST NONCE the
      task cannot predict (generated by `core/serve.py post_exec`, handed
      to the client out-of-band as the `X-Mship-Exec-Nonce` response header
      — sent before the streamed body, so the task can never inject it).
      Without the nonce tag a control line is just ordinary task output:
      a remote branch that prints a bare `__MSHIP_EXIT__ 0` can NOT
      green-wash a failed build.
    - For `verb == "capture"` ONLY, if the task exits 0 and produces at
      least one artifact (`capture.discover_artifacts` on the remote's
      `MSHIP_CAPTURE_DIR`), a length-prefixed tar block is emitted after
      that repo's task lines and before the exit sentinel:
          __MSHIP_ARTIFACTS__:<nonce> <byte_count>\\n
          <exactly byte_count bytes of UNCOMPRESSED tar, containing the
           discovered artifact files at their basenames, e.g. screen.png,
           layout.json>
      `<byte_count>` is a base-10 int. The client must read exactly that
      many raw bytes as the tar (binary-safe — do NOT line-split them)
      before resuming line-based reads. No block is emitted when capture
      produced no artifacts; instead a capture that exits 0 with NO
      recognized artifact is turned into an ERROR (an error line + a
      non-zero exit code), matching local `capture.run_capture`. `run`/
      `build` never emit an artifact block.
    - The LAST line always matches `__MSHIP_EXIT__:<nonce> <code>\\n` where
      <code> is a base-10 int (0 == success). This conveys the remote
      task's exit code as DATA, never as an HTTP error status — a non-zero
      task exit does not raise; the client must parse this trailing line
      (matched against its nonce) to learn the real result and mirror it as
      its own process exit code.
"""

from __future__ import annotations

from pathlib import Path
import errno
import hashlib
import io
import json
import os
import re
import secrets
import shlex
import shutil
import stat
import sys
import tarfile
import tempfile
import threading
import time
from collections.abc import Callable, Generator, Mapping, Sequence
from dataclasses import dataclass, replace
from typing import Iterator, Protocol

try:
    import fcntl
except ModuleNotFoundError:
    fcntl = None

from mship.core import capture as _cap
from mship.core import remote_setup
from mship.core.config import WorkspaceConfig
from mship.core import host_tools
from mship.core.remote_tool import ToolContext, ToolEvent, ToolRequest, ToolResult
from mship.core.run_ref import RunRefNameError, canonical_run_ref_segment
from mship.core.tool_process import ToolOperationRegistry
from mship.core.task_result_publication import (
    AuthenticatedExecutionProvenance,
    TaskResultPublisher,
)
from mship.core.task_results import TaskResultStore
from mship.core.session_channel import (
    CLAIM_TTL_SECONDS,
    OwnerClient,
    OwnerContext,
    decode_private_json,
)
from mship.core.session_inputs import (
    OwnerRequest,
    SessionError,
    identifier,
    strict_object,
)
from mship.core.session_runtime import (
    SESSION_RESERVED_INPUTS,
    SessionPreparation,
)
from mship.core.run_target.models import BackendConfig, DiscoveryRequest
from mship.core.run_target.host import (
    TARGET_BINDINGS_FILE,
    TARGET_CONTEXT_FILE,
    TARGET_REQUEST_FILE,
    owner_profile_input_files,
    _decode_profile_json,
)
from mship.core.run_ref import run_ref as build_run_ref
from mship.util.shell import (
    ShellCancellationUnsupported,
    ShellCancelled,
    ensure_cancellable_shell_supported,
)
from mship.util.taskfile import taskfile_has_target

VERBS: tuple[str, ...] = ("run", "capture", "build")

# Trailing sentinel line: `f"{EXIT_MARKER}:{nonce} {code}\n"` — the `:{nonce}`
# tag (a per-request secret handed to the client via the X-Mship-Exec-Nonce
# response header) is what stops task stdout from spoofing the exit code. See
# the module docstring for the full wire contract Task 5's client must parse.
EXIT_MARKER = "__MSHIP_EXIT__"

# Length-prefixed tar block marker (capture only):
# `f"{ARTIFACT_MARKER}:{nonce} {len(tar_bytes)}\n"` immediately followed by
# exactly that many raw (uncompressed) tar bytes. Nonce-tagged for the same
# anti-spoof reason as EXIT_MARKER. See module docstring for the full framing.
ARTIFACT_MARKER = "__MSHIP_ARTIFACTS__"


class UnknownVerbError(ValueError):
    """`verb` is not one of `VERBS`."""


class MaterializeError(Exception):
    """A git plumbing command needed to bring a repo's task-branch worktree
    up to date (fetch, checkout, reset, or worktree add) exited non-zero.

    Raised by `materialize_worktree`/`_run_checked` and caught by
    `run_verb_stream`, which turns it into a clean stream error (an error
    line naming the repo + failing command, then a non-zero `__MSHIP_EXIT__`)
    rather than silently running the task against a missing/stale worktree
    (Task 6 hardening — see the module docstring's wire contract)."""


class ShellLike(Protocol):
    """The subset of `mship.util.shell.ShellRunner` this module needs.
    `.run_argv` issues git plumbing; `.spawn_argv` launches the selected
    tool with structured arguments and an exact server-owned environment.
    Process supervision belongs to ToolOperationRegistry."""

    def run_argv(
        self,
        args: Sequence[str],
        cwd: Path,
        env: dict[str, str] | None = None,
        *,
        cancel_event: threading.Event | None = None,
    ): ...

    def spawn_argv(self, args: Sequence[str], cwd: Path | int, env: dict[str, str]): ...


@dataclass
class RemoteExecDeps:
    """Collaborators `run_verb_stream` needs, injected so tests can fake
    them without touching a real filesystem/subprocess/git checkout.

    `config` is THIS machine's own `WorkspaceConfig` (its own repo paths —
    which generally differ from the operator's machine's paths, hence this
    can't be sent over the wire and must be resolved locally). `shell` does
    double duty for git commands and the streamed task run (see
    `ShellLike`). `workspace_root` anchors where remote worktrees live:
    `<workspace_root>/.worktrees/<task>/<repo>`, mirroring the local
    `WorktreeManager` hub layout. `cancel_event` requests cleanup of processes
    that remain in the spawned POSIX process group when the client disconnects;
    the public runner rejects hosts that cannot provide that guarantee before
    taking the lock.
    """

    config: WorkspaceConfig
    shell: ShellLike
    workspace_root: Path
    cancel_event: threading.Event | None = None
    operations: ToolOperationRegistry | None = None
    result_store: TaskResultStore | None = None
    execution_provenance: AuthenticatedExecutionProvenance | None = None
    work_item_id_for_task: Callable[[str], str | None] | None = None


def _hub_dir(workspace_root: Path, task: str) -> Path:
    return workspace_root / ".worktrees" / task


def _acquire_task_execution_lock(
    workspace_root: Path,
    task: str,
) -> io.TextIOWrapper:
    if fcntl is None:
        raise OSError("POSIX file locking is unavailable")

    lock_dir = workspace_root / ".mothership" / "remote-exec-locks"
    lock_dir.mkdir(parents=True, exist_ok=True)
    digest = hashlib.sha256(task.encode("utf-8")).hexdigest()
    lock_file = (lock_dir / f"{digest}.lock").open("a+")
    try:
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError as exc:
        lock_file.close()
        if exc.errno in {errno.EACCES, errno.EAGAIN, errno.EWOULDBLOCK}:
            raise BlockingIOError(exc.errno, exc.strerror) from exc
        raise
    except BaseException:
        lock_file.close()
        raise
    return lock_file


def _run_shell(
    shell: ShellLike,
    args: Sequence[str],
    cwd: Path,
    *,
    cancel_event: threading.Event | None,
):
    return shell.run_argv(
        args,
        cwd=cwd,
        cancel_event=cancel_event,
    )


def _git_rev(
    shell: ShellLike,
    cwd: Path,
    ref: str,
    *,
    cancel_event: threading.Event | None = None,
) -> str | None:
    result = _run_shell(
        shell,
        ["git", "rev-parse", ref],
        cwd,
        cancel_event=cancel_event,
    )
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def check_base_freshness(
    shell: ShellLike,
    repo_path: Path,
    base_branch: str | None,
    *,
    cancel_event: threading.Event | None = None,
) -> str | None:
    """MOS-203: before materializing, make sure this repo's knowledge of the
    task's base branch is current — auto-fetch it and, if origin had moved,
    return a warning line (str, no trailing newline) to surface into the
    stream. A remote run that silently sat on a stale base would build old
    code with no visible signal, hence the fold-in.

    Returns None when there's no base_branch to check, or when the fetch
    didn't move anything (already current) — a warning is only emitted when
    origin genuinely had new commits we didn't have yet.
    """
    if not base_branch:
        return None
    before = _git_rev(
        shell,
        repo_path,
        f"origin/{base_branch}",
        cancel_event=cancel_event,
    )
    _run_shell(
        shell,
        ["git", "fetch", "origin", base_branch],
        repo_path,
        cancel_event=cancel_event,
    )
    after = _git_rev(
        shell,
        repo_path,
        f"origin/{base_branch}",
        cancel_event=cancel_event,
    )
    if before is not None and after is not None and before != after:
        return (
            f"warning: base '{base_branch}' was behind origin "
            f"({before[:7]} -> {after[:7]}) — auto-fetched before materializing."
        )
    return None


def _run_checked(
    shell: ShellLike,
    args: Sequence[str],
    cwd: Path,
    *,
    repo_name: str,
    cancel_event: threading.Event | None = None,
) -> None:
    """Run a git plumbing command that MUST succeed for the branch worktree
    to be usable. Raises `MaterializeError` (naming the repo, the failing
    command, and its stderr) on a non-zero exit rather than letting
    `run_verb_stream` continue on to run the task against a missing/stale
    worktree (Task 6 hardening — previously every `materialize_worktree`
    call site ignored `ShellResult.returncode` entirely)."""
    result = _run_shell(
        shell,
        args,
        cwd,
        cancel_event=cancel_event,
    )
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        detail = f": {stderr}" if stderr else f" (exit {result.returncode})"
        command = shlex.join(args)
        raise MaterializeError(
            f"branch-materialize failed for repo {repo_name!r}: `{command}`{detail}"
        )


def materialize_worktree(
    shell: ShellLike,
    repo_path: Path,
    worktree_path: Path,
    branch: str,
    *,
    repo_name: str,
    run_ref: str | None = None,
    cancel_event: threading.Event | None = None,
) -> None:
    """Ensure `worktree_path` is a git worktree of `repo_path` holding the
    revision this run is supposed to execute.

    Two modes.

    `run_ref` GIVEN (spec remote-exact-copy): the operator pushed a commit
    synthesized from their working tree straight to this host, so the revision is
    ALREADY in this repository. Materialization is a reset to a LOCAL ref with NO
    FETCH — origin is not consulted at all, which is also why the caller skips
    the base-freshness probe for these repos. HEAD is left DETACHED on purpose:
    the scratch commit is throwaway state, and pointing a branch at it would
    dress it up as history. `git clean -fd` removes leftovers from a previous
    run so the result is an exact copy; it does not remove gitignored files, so
    dependencies derived by `task setup` survive between runs.

    `run_ref` NONE (unchanged from before): `branch` already exists on origin
    (created by `mship spawn`/dispatch on the operator's machine and pushed
    there) — this NEVER creates a new branch here, it only fetches + tracks the
    existing one. Idempotent: an existing worktree is fetched + hard-reset to the
    new tip; a first-time run creates it with `git worktree add -B`, which is
    safe to re-run even if a stale local branch ref of the same name exists.

    Every git command runs through `_run_checked` (`repo_name` is only used for
    that error message): a failure here raises `MaterializeError` instead of
    silently letting execution continue against a missing/stale checkout.
    """
    if run_ref is not None:
        if (worktree_path / ".git").exists():
            # `checkout --detach` with NO ref keeps the current commit, so it
            # succeeds even when the worktree is dirty from the last run
            # (verified); the reset then moves detached HEAD without ever moving
            # a branch.
            _run_checked(
                shell,
                ["git", "checkout", "--detach"],
                worktree_path,
                repo_name=repo_name,
                cancel_event=cancel_event,
            )
            _run_checked(
                shell,
                ["git", "reset", "--hard", run_ref],
                worktree_path,
                repo_name=repo_name,
                cancel_event=cancel_event,
            )
            _run_checked(
                shell,
                ["git", "clean", "-fd"],
                worktree_path,
                repo_name=repo_name,
                cancel_event=cancel_event,
            )
        else:
            worktree_path.parent.mkdir(parents=True, exist_ok=True)
            _run_checked(
                shell,
                [
                    "git",
                    "worktree",
                    "add",
                    "--detach",
                    str(worktree_path),
                    run_ref,
                ],
                repo_path,
                repo_name=repo_name,
                cancel_event=cancel_event,
            )
        return

    _run_checked(
        shell,
        ["git", "fetch", "origin", branch],
        repo_path,
        repo_name=repo_name,
        cancel_event=cancel_event,
    )
    if (worktree_path / ".git").exists():
        _run_checked(
            shell,
            ["git", "fetch", "origin", branch],
            worktree_path,
            repo_name=repo_name,
            cancel_event=cancel_event,
        )
        _run_checked(
            shell,
            ["git", "checkout", branch],
            worktree_path,
            repo_name=repo_name,
            cancel_event=cancel_event,
        )
        _run_checked(
            shell,
            ["git", "reset", "--hard", f"origin/{branch}"],
            worktree_path,
            repo_name=repo_name,
            cancel_event=cancel_event,
        )
    else:
        worktree_path.parent.mkdir(parents=True, exist_ok=True)
        _run_checked(
            shell,
            [
                "git",
                "worktree",
                "add",
                "-B",
                branch,
                str(worktree_path),
                f"origin/{branch}",
            ],
            repo_path,
            repo_name=repo_name,
            cancel_event=cancel_event,
        )


class _CaptureDigestReader(io.BufferedReader):
    def __init__(self, raw: io.RawIOBase):
        super().__init__(raw)
        self.digest = hashlib.sha256()

    def read(self, size: int | None = -1) -> bytes:
        data = super().read(size)
        self.digest.update(data)
        return data


def _build_artifact_tar(
    artifacts: list[_cap.Artifact],
    *,
    directory_fd: int | None = None,
    max_bytes: int | None = None,
    expected_artifacts: Mapping[str, tuple[int, str]] | None = None,
) -> bytes:
    """Use the existing basename-only tar envelope; session reads stay fd-pinned."""
    buf = io.BytesIO()
    total = 0
    with tarfile.open(fileobj=buf, mode="w") as tar:
        for artifact in artifacts:
            if directory_fd is None:
                tar.add(artifact.path, arcname=artifact.path.name)
                continue
            expected = (
                None
                if expected_artifacts is None
                else expected_artifacts.get(artifact.path.name)
            )
            if expected is None:
                raise OSError("capture artifact has no owner acknowledgement")
            fd = os.open(
                artifact.path.name,
                os.O_RDONLY | os.O_NONBLOCK | os.O_NOFOLLOW,
                dir_fd=directory_fd,
            )
            with _CaptureDigestReader(io.FileIO(fd, "rb", closefd=True)) as stream:
                info = os.fstat(stream.fileno())
                if (
                    not stat.S_ISREG(info.st_mode)
                    or info.st_nlink != 1
                    or info.st_size <= 0
                ):
                    raise OSError("capture artifact is not a private regular file")
                if info.st_size != expected[0]:
                    raise OSError(
                        "capture artifact size does not match owner acknowledgement"
                    )
                total += info.st_size
                if max_bytes is not None and total + 32 * 1024 > max_bytes:
                    raise OSError("capture artifacts exceed the transfer limit")
                member = tarfile.TarInfo(artifact.path.name)
                member.size = info.st_size
                member.mode = 0o600
                tar.addfile(member, stream)
                if stream.digest.hexdigest() != expected[1]:
                    raise OSError(
                        "capture artifact bytes do not match owner acknowledgement"
                    )
                after = os.fstat(stream.fileno())
                if (after.st_size, after.st_mtime_ns, after.st_ctime_ns) != (
                    info.st_size,
                    info.st_mtime_ns,
                    info.st_ctime_ns,
                ):
                    raise OSError("capture artifact changed while being collected")
    return buf.getvalue()


def run_verb_stream(
    verb: str,
    task: str,
    repos: list[str],
    platform: str | None,
    *,
    deps: RemoteExecDeps,
    kind: str = "all",
    nonce: str,
    run_ref_repos: list[str] | None = None,
) -> Iterator[bytes]:
    """Legacy wire adapter over the shared preparation/process owner."""
    try:
        ensure_cancellable_shell_supported()
        task = canonical_run_ref_segment(task)
    except ShellCancellationUnsupported, RunRefNameError:
        yield b"error: remote execution unavailable; execution was not started\n"
        yield f"{EXIT_MARKER}:{nonce} 1\n".encode()
        return
    try:
        lock_file = _acquire_task_execution_lock(deps.workspace_root, task)
    except BlockingIOError:
        yield (
            f"error: remote task {task!r} is already running; "
            "try again after it finishes\n"
        ).encode()
        yield f"{EXIT_MARKER}:{nonce} 2\n".encode()
        return
    except OSError, UnicodeError:
        yield b"error: remote-task locking failed; execution was not started\n"
        yield f"{EXIT_MARKER}:{nonce} 1\n".encode()
        return
    try:
        admission = _operations(deps).admission_status(task)
        if admission != "available":
            yield f"error: remote task execution ownership is {admission}\n".encode()
            yield f"{EXIT_MARKER}:{nonce} 2\n".encode()
            return
        yield from _run_verb_stream_unlocked(
            verb,
            task,
            repos,
            platform,
            deps=deps,
            kind=kind,
            nonce=nonce,
            run_ref_repos=run_ref_repos,
        )
    finally:
        try:
            fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)
        finally:
            lock_file.close()


class _PreparationError(Exception):
    def __init__(self, status: str, message: str, exit_code: int = 1):
        super().__init__(message)
        self.status = status
        self.exit_code = exit_code


def _operations(deps: RemoteExecDeps) -> ToolOperationRegistry:
    if deps.operations is None:
        deps.operations = ToolOperationRegistry(deps.workspace_root)
    return deps.operations


class _PreparedTask:
    """One server-owned source preparation, shared by every adapter."""

    def __init__(
        self,
        deps: RemoteExecDeps,
        task: str,
        repos: Sequence[str],
        run_ref_repos: Sequence[str],
    ):
        self.deps = deps
        self.task = canonical_run_ref_segment(task)
        self.hub = _hub_dir(deps.workspace_root, self.task)
        if not self.hub.resolve().is_relative_to(deps.workspace_root.resolve()):
            raise _PreparationError("invalid", "task worktree escapes workspace", 2)
        self.branch = deps.config.branch_pattern.replace("{slug}", self.task)
        names = {name: name for name in deps.config.repos}
        unknown = [name for name in (*repos, *run_ref_repos) if name not in names]
        if unknown:
            raise _PreparationError(
                "invalid",
                f"unknown repo(s) {', '.join(unknown)}; known repos: "
                f"{', '.join(sorted(names)) or '(none)'}",
                2,
            )
        self.repos = [names[name] for name in repos]
        self.run_refs: dict[str, str] = {}
        for name in set(run_ref_repos):
            try:
                self.run_refs[names[name]] = build_run_ref(self.task, names[name])
            except RunRefNameError as exc:
                raise _PreparationError(
                    "invalid",
                    "cannot build a run ref for this request",
                    2,
                ) from exc
        self.materialized: dict[str, Path] = {}

    def _top(self, name: str) -> Generator[bytes, None, Path]:
        if name in self.materialized:
            return self.materialized[name]
        deps = self.deps
        config = deps.config.repos[name]
        path = self.hub / name
        if not path.resolve().is_relative_to(self.hub.resolve()):
            raise _PreparationError("invalid", "repository worktree escapes task", 2)
        ref = self.run_refs.get(name)
        try:
            if ref is None:
                warning = check_base_freshness(
                    deps.shell,
                    config.path,
                    config.base_branch,
                    cancel_event=deps.cancel_event,
                )
                if warning is not None:
                    yield f"{warning}\n".encode()
            materialize_worktree(
                deps.shell,
                config.path,
                path,
                self.branch,
                repo_name=name,
                run_ref=ref,
                cancel_event=deps.cancel_event,
            )
        except MaterializeError as exc:
            raise _PreparationError("materialization_error", str(exc)) from exc
        self.materialized[name] = path
        return path

    def prepare(self, name: str) -> Generator[bytes, None, Path]:
        config = self.deps.config.repos[name]
        if config.git_root is not None:
            parent = yield from self._top(config.git_root)
            path = parent / config.path
            if not path.resolve().is_relative_to(parent.resolve()):
                raise _PreparationError("invalid", "child repository escapes parent", 2)
            self.materialized[name] = path
        else:
            path = yield from self._top(name)
        return path

    def context(self, name: str) -> ToolContext:
        try:
            path = self.materialized[name].resolve(strict=True)
        except OSError as exc:
            raise _PreparationError(
                "materialization_error",
                "prepared worktree is unavailable",
            ) from exc
        if not path.is_relative_to(self.hub.resolve()) or not path.is_relative_to(
            self.deps.workspace_root.resolve()
        ):
            raise _PreparationError("invalid", "prepared worktree escapes workspace", 2)
        revision = _git_rev(
            self.deps.shell,
            path,
            "HEAD",
            cancel_event=self.deps.cancel_event,
        )
        if (
            revision is None
            or re.fullmatch(r"(?:[0-9a-f]{40}|[0-9a-f]{64})", revision) is None
        ):
            raise _PreparationError(
                "materialization_error",
                "cannot verify prepared source identity",
            )
        return ToolContext(
            task=self.task,
            repo=name,
            worktree=path,
            source_revision=revision,
            env_runner=self.deps.config.repos[name].env_runner
            or self.deps.config.env_runner,
        )


def _setup_events(
    prepared: _PreparedTask, name: str, context: ToolContext
) -> Generator[ToolEvent, None, None]:
    deps = prepared.deps
    config = deps.config.repos[name]
    actual = config.tasks.get("setup", "setup")
    if "setup" in config.not_applicable or not taskfile_has_target(
        context.worktree, actual
    ):
        yield ToolEvent("result", result=ToolResult("completed", exit_code=0))
        return
    key = remote_setup.setup_key(context.worktree, config.setup_inputs)
    key_path = remote_setup.key_file(deps.workspace_root, prepared.task, name)
    if not remote_setup.needs_setup(key_path, key):
        yield ToolEvent("result", result=ToolResult("completed", exit_code=0))
        return
    setup_argv: tuple[str, ...] = ("task", actual)
    setup_env: dict[str, str] = {}
    if config.host_tools is not None:
        setup_argv = ("mise", "exec", "--", "task", actual)
        setup_env = host_tools.mise_environment(
            worktree=context.worktree,
            state_dir=deps.workspace_root / ".mothership",
            declaration=config.host_tools,
            safe=False,
        )
    request = ToolRequest(task=prepared.task, repo=name, argv=setup_argv, env=setup_env)
    stream = _operations(deps).run(
        request,
        context,
        cancel_event=deps.cancel_event,
        spawn=deps.shell.spawn_argv,
    )
    try:
        for event in stream:
            if event.kind == "result" and event.result is not None:
                if event.result.status == "completed" and event.result.exit_code == 0:
                    verified = prepared.context(name)
                    if (
                        verified.source_revision != context.source_revision
                        or verified.worktree != context.worktree
                    ):
                        raise _PreparationError(
                            "materialization_error",
                            "setup changed prepared source identity",
                        )
                    remote_setup.record_setup(key_path, key)
            yield event
    finally:
        stream.close()


def _legacy_events(events: Iterator[ToolEvent]) -> Generator[bytes, None, ToolResult]:
    """Adapt bounded binary events; never assemble a complete output line."""
    last_byte: bytes = b"\n"
    result = ToolResult("protocol_error")
    try:
        for event in events:
            if event.kind in {"stdout", "stderr"} and event.data:
                last_byte = event.data[-1:]
                yield event.data
            elif event.kind == "result" and event.result is not None:
                result = event.result
    finally:
        close = getattr(events, "close", None)
        if close is not None:
            close()
    # Keep a newline-free final output fragment from swallowing the next
    # legacy control record. Structured tool frames do not need this separator.
    if last_byte != b"\n":
        yield b"\n"
    return result


def _legacy_code(result: ToolResult) -> int:
    if result.status == "completed":
        return result.exit_code if result.exit_code is not None else 1
    return 2 if result.status in {"invalid", "busy"} else 1


def _run_verb_stream_unlocked(
    verb: str,
    task: str,
    repos: list[str],
    platform: str | None,
    *,
    deps: RemoteExecDeps,
    kind: str = "all",
    nonce: str,
    run_ref_repos: list[str] | None = None,
) -> Iterator[bytes]:
    if verb not in VERBS:
        raise UnknownVerbError(f"unknown verb {verb!r}; expected one of {VERBS}")
    kinds = _cap.resolve_kinds(kind) if verb == "capture" else None
    exit_code = 0
    try:
        prepared = _PreparedTask(deps, task, repos, run_ref_repos or ())
        for name in prepared.repos:
            yield from prepared.prepare(name)
            context = prepared.context(name)
            setup = yield from _legacy_events(_setup_events(prepared, name, context))
            if setup.status == "cancelled":
                return
            if setup.status != "completed" or setup.exit_code != 0:
                exit_code = _legacy_code(setup)
                yield (
                    f"error: setup failed on the run host for repo {name!r} "
                    f"(exit {exit_code}); the {verb} was not started.\n"
                ).encode()
                break
            out_dir: Path | None = None
            try:
                env: dict[str, str] = {}
                if verb == "capture":
                    out_dir = Path(tempfile.mkdtemp(prefix="mship-remote-capture-"))
                    env = {
                        "MSHIP_CAPTURE_DIR": str(out_dir),
                        "MSHIP_CAPTURE_KINDS": ",".join(kinds or []),
                    }
                    if platform is not None:
                        env["MSHIP_CAPTURE_PLATFORM"] = platform
                actual = deps.config.repos[name].tasks.get(verb, verb)
                request = ToolRequest(
                    task=task, repo=name, argv=("task", actual), env=env
                )
                result = yield from _legacy_events(
                    _operations(deps).run(
                        request,
                        context,
                        cancel_event=deps.cancel_event,
                        spawn=deps.shell.spawn_argv,
                    )
                )
                if result.status == "cancelled":
                    return
                exit_code = _legacy_code(result)
                if result.status != "completed":
                    yield f"error: remote execution {result.status}\n".encode()
                if verb == "capture" and exit_code == 0:
                    artifacts = _cap.discover_artifacts(out_dir, kinds or [])
                    if artifacts:
                        data = _build_artifact_tar(artifacts)
                        yield f"{ARTIFACT_MARKER}:{nonce} {len(data)}\n".encode()
                        yield data
                    else:
                        yield (
                            f"error: capture target produced no recognized artifact "
                            f"in {out_dir} for kinds {kinds or []}.\n"
                        ).encode()
                        exit_code = 1
            finally:
                if out_dir is not None:
                    shutil.rmtree(out_dir, ignore_errors=True)
            if exit_code != 0:
                break
    except _PreparationError as exc:
        yield f"error: {exc}\n".encode()
        exit_code = exc.exit_code
    except ShellCancelled:
        return
    except OSError, ValueError:
        yield b"error: remote execution preparation or evidence failed\n"
        exit_code = 1
    yield f"{EXIT_MARKER}:{nonce} {exit_code}\n".encode()


def _host_tool_runner(
    *,
    command: host_tools.HostToolCommand,
    context: ToolContext,
    deps: RemoteExecDeps,
) -> host_tools.HostToolInvocation:
    """Run one server-created mise/catalog probe through the existing owner."""
    request = ToolRequest(
        task=context.task,
        repo=context.repo,
        argv=command.argv,
        env=command.environment,
        preparation="launch" if command.mutating else "discover",
        max_stdout_bytes=None if command.mutating else 64 * 1024,
        max_stderr_bytes=None if command.mutating else 16 * 1024,
        timeout_seconds=None if command.mutating else 20,
    )
    probe_context = replace(context, env_runner=None)
    events = _operations(deps).run(
        request,
        probe_context,
        cancel_event=deps.cancel_event,
        spawn=deps.shell.spawn_argv,
    )
    result = ToolResult("protocol_error")
    try:
        for event in events:
            if event.kind == "result" and event.result is not None:
                result = event.result
    finally:
        events.close()
    return host_tools.HostToolInvocation(
        status=result.status,
        exit_code=result.exit_code,
        stdout=result.stdout,
        stderr=result.stderr,
    )


def _host_tool_report(
    request: ToolRequest, context: ToolContext, *, deps: RemoteExecDeps
) -> ToolResult | None:
    """Resolve a typed host-tools request after server source materialization."""
    if request.host_tools_action is None:
        return None
    declaration = deps.config.repos[request.repo].host_tools
    if declaration is None:
        resolution = host_tools.HostToolResolution(
            host_tools.server_identity(deps.workspace_root / ".mothership"),
            context.task,
            context.repo,
            context.source_revision,
            None,
            None,
            None,
            "invalid_configuration",
        )
    else:
        state_dir = deps.workspace_root / ".mothership"
        identity = host_tools.server_identity(state_dir)
        runner = lambda command: _host_tool_runner(
            command=command, context=context, deps=deps
        )
        if request.host_tools_action == "bootstrap":
            resolution = host_tools.bootstrap(
                declaration=declaration,
                worktree=context.worktree,
                state_dir=state_dir,
                identity=identity,
                task=context.task,
                repo=context.repo,
                source_revision=context.source_revision,
                run=runner,
            )
        else:
            resolution = host_tools.diagnose(
                declaration=declaration,
                worktree=context.worktree,
                state_dir=state_dir,
                identity=identity,
                task=context.task,
                repo=context.repo,
                source_revision=context.source_revision,
                run=runner,
            )
    report = host_tools.doctor_report(resolution).safe_dict()
    return ToolResult(
        "completed",
        exit_code=0,
        host_tools_report=report,
    )


def _bootstrap_host_tool_events(
    request: ToolRequest, context: ToolContext, *, deps: RemoteExecDeps
) -> Generator[ToolEvent, None, None]:
    """Bootstrap once, forwarding the actual install stream before its report."""
    declaration = deps.config.repos[request.repo].host_tools
    state_dir = deps.workspace_root / ".mothership"
    if declaration is None:
        report = _host_tool_report(request, context, deps=deps)
        yield ToolEvent("result", result=report or ToolResult("invalid"))
        return
    identity = host_tools.server_identity(state_dir)
    runner = lambda command: _host_tool_runner(
        command=command, context=context, deps=deps
    )
    resolution = host_tools.diagnose(
        declaration=declaration,
        worktree=context.worktree,
        state_dir=state_dir,
        identity=identity,
        task=context.task,
        repo=context.repo,
        source_revision=context.source_revision,
        run=runner,
    )
    if resolution.status == "healthy":
        host_tools.record_receipt(state_dir, resolution)
        yield ToolEvent(
            "result",
            result=ToolResult(
                "completed",
                exit_code=0,
                host_tools_report=host_tools.doctor_report(resolution).safe_dict(),
            ),
        )
        return
    if resolution.status in {"invalid_configuration", "missing_mise"}:
        yield ToolEvent(
            "result",
            result=ToolResult(
                "completed",
                exit_code=1,
                host_tools_report=host_tools.doctor_report(resolution).safe_dict(),
            ),
        )
        return
    environment = host_tools.mise_environment(
        worktree=context.worktree,
        state_dir=state_dir,
        declaration=declaration,
        locked=resolution.lock_digest is not None,
        safe=False,
    )
    install = ToolRequest(
        task=context.task,
        repo=context.repo,
        argv=("mise", "install"),
        env=environment,
        preparation="launch",
    )
    stream = _operations(deps).run(
        install,
        replace(context, env_runner=None),
        cancel_event=deps.cancel_event,
        spawn=deps.shell.spawn_argv,
    )
    outcome = ToolResult("protocol_error")
    owner: ToolResult | None = None
    try:
        for event in stream:
            if event.kind == "started" and event.result is not None:
                owner = event.result
                yield event
            elif event.kind in {"stdout", "stderr"}:
                yield event
            elif event.kind == "result" and event.result is not None:
                outcome = event.result
    finally:
        stream.close()
    if outcome.status == "completed" and outcome.exit_code == 0:
        resolution = host_tools.diagnose(
            declaration=declaration,
            worktree=context.worktree,
            state_dir=state_dir,
            identity=identity,
            task=context.task,
            repo=context.repo,
            source_revision=context.source_revision,
            run=runner,
        )
        if resolution.status == "healthy":
            host_tools.record_receipt(state_dir, resolution)
    result = ToolResult(
        "completed",
        exit_code=0 if resolution.status == "healthy" else 1,
        owner_ref=None if owner is None else owner.owner_ref,
        generation=None if owner is None else owner.generation,
        source_revision=None if owner is None else owner.source_revision,
        host_tools_report=host_tools.doctor_report(resolution).safe_dict(),
    )
    yield ToolEvent("result", result=result)


def _resolve_host_tools_for_launch(
    request: ToolRequest, context: ToolContext, *, deps: RemoteExecDeps
) -> ToolResult | ToolRequest | None:
    """Gate setup and launch on server-side readiness; never provision here."""
    declaration = deps.config.repos[request.repo].host_tools
    if declaration is None:
        return request
    state_dir = deps.workspace_root / ".mothership"
    resolution = host_tools.diagnose(
        declaration=declaration,
        worktree=context.worktree,
        state_dir=state_dir,
        identity=host_tools.server_identity(state_dir),
        task=context.task,
        repo=context.repo,
        source_revision=context.source_revision,
        run=lambda command: _host_tool_runner(
            command=command, context=context, deps=deps
        ),
    )
    if resolution.status != "healthy":
        return ToolResult(
            "completed",
            exit_code=1,
            host_tools_report=host_tools.doctor_report(resolution).safe_dict(),
        )
    actual = (
        request.argv[1]
        if len(request.argv) == 2 and request.argv[0] == "task"
        else None
    )
    if actual is None:
        return None
    if any(key.startswith("MISE_") for key in request.env):
        return ToolResult("invalid")
    environment = host_tools.mise_environment(
        worktree=context.worktree,
        state_dir=state_dir,
        declaration=declaration,
        safe=False,
    )
    return replace(
        request,
        argv=("mise", "exec", "--", "task", actual),
        env={**request.env, **environment},
    )


def _session_configuration(
    request: ToolRequest, deps: RemoteExecDeps
) -> tuple[DiscoveryRequest, BackendConfig] | None:
    payload = request.input_files.get(TARGET_REQUEST_FILE)
    if payload is None:
        return None
    profile_request = DiscoveryRequest.model_validate(_decode_profile_json(payload))
    repo = deps.config.repos.get(request.repo)
    if repo is None:
        return None
    backend = repo.run_backends.get(profile_request.backend)
    if backend is None or backend.session_owner is None:
        return None
    return profile_request, backend


def _resolve_tool_request(
    request: ToolRequest, *, deps: RemoteExecDeps
) -> ToolRequest | None:
    """Resolve configured task keys and host-only profile inputs before launch."""
    repo_config = deps.config.repos.get(request.repo)
    if repo_config is None:
        return None
    if SESSION_RESERVED_INPUTS & (request.input_files.keys() | request.env.keys()):
        return None
    if request.host_tools_action is not None:
        if request.env or request.input_files or request.task_key is not None:
            return None
        expected = "discover" if request.host_tools_action == "diagnose" else "launch"
        if request.preparation != expected:
            return None
        return request
    try:
        session_config = _session_configuration(request, deps)
        parent_inputs = None
        if session_config is not None:
            if session_config[0].operation.startswith("source-"):
                return None
            if request.env or set(request.input_files) - {
                TARGET_REQUEST_FILE,
                TARGET_CONTEXT_FILE,
                "MSHIP_SESSION_OPERATION_FILE",
            }:
                return None
            if request.preparation == "observe":
                if request.owner_ref is None or request.generation is None:
                    return None
                parent = _operations(deps).session_for_owner(
                    task=request.task,
                    repo=request.repo,
                    owner_ref=request.owner_ref,
                    generation=request.generation,
                )
                if parent is None:
                    return None
                _, parent_inputs = parent
            action = request.input_files.get("MSHIP_SESSION_OPERATION_FILE")
            if action is not None:
                _decode_profile_json(action)
        elif request.install_from_result is not None:
            return None
        profile_inputs = {
            TARGET_REQUEST_FILE,
            TARGET_CONTEXT_FILE,
            TARGET_BINDINGS_FILE,
        } & request.input_files.keys()
        input_files = (
            owner_profile_input_files(
                request.input_files,
                task=request.task,
                repo=request.repo,
                config=repo_config,
                task_key=request.task_key,
                preparation=request.preparation,
                source_revision=request.source_revision,
                parent_input_files=parent_inputs,
            )
            if request.task_key is not None or profile_inputs
            else dict(request.input_files)
        )
        if request.task_key is None:
            return replace(request, input_files=input_files)
        actual = repo_config.tasks.get(request.task_key)
        if actual is None:
            return None
        return replace(
            request,
            argv=("task", actual),
            task_key=None,
            input_files=input_files,
            install_from_result=None,
        )
    except TypeError, ValueError:
        return None


def run_tool_stream(
    request: ToolRequest,
    *,
    deps: RemoteExecDeps,
    capture_kinds: tuple[str, ...] | None = None,
    capture_platform: str | None = None,
    on_session_prepared: Callable[[OwnerContext], None] | None = None,
    source_update_id: str | None = None,
    owner_operation: str | None = None,
) -> Generator[ToolEvent, None, None]:
    """Execute one typed tool operation without a second transport/owner."""
    task_key = request.task_key
    install_from_result = request.install_from_result
    resolved = _resolve_tool_request(request, deps=deps)
    if resolved is None:
        yield ToolEvent("result", result=ToolResult("invalid"))
        return
    request = resolved
    try:
        session_config = _session_configuration(request, deps)
        if session_config is not None:
            request = replace(request, env={"MSHIP_SESSION_PYTHON": sys.executable})
        session = None
        if session_config is not None and request.preparation != "discover":
            profile_request, backend = session_config
            session = SessionPreparation(
                operation=profile_request.operation,
                owner_kind=backend.session_owner or "",
                sealed_context=request.input_files.get(TARGET_CONTEXT_FILE),
                install=install_from_result,
                result_store=deps.result_store,
                capture_kinds=capture_kinds,
                capture_platform=capture_platform,
            )
            if owner_operation is not None:
                if (
                    owner_operation != "source-release"
                    or source_update_id is None
                    or session.owner_kind != "flutter"
                ):
                    raise SessionError("invalid", "Invalid internal source operation")
                session = replace(session, operation=owner_operation)
        elif capture_kinds is not None or install_from_result is not None:
            yield ToolEvent("result", result=ToolResult("invalid"))
            return
    except ValueError, SessionError:
        yield ToolEvent("result", result=ToolResult("invalid"))
        return
    operations = _operations(deps)
    if request.preparation == "observe":
        stream = operations.observe(
            request,
            cancel_event=deps.cancel_event,
            spawn=deps.shell.spawn_argv,
            session=session,
            on_session_prepared=on_session_prepared,
            source_update_id=source_update_id,
        )
        try:
            yield from stream
        finally:
            stream.close()
        return
    try:
        ensure_cancellable_shell_supported()
    except ShellCancellationUnsupported:
        yield ToolEvent("result", result=ToolResult("unsupported"))
        return
    try:
        lock_file = _acquire_task_execution_lock(deps.workspace_root, request.task)
    except BlockingIOError:
        yield ToolEvent("result", result=ToolResult("busy"))
        return
    except OSError, UnicodeError:
        yield ToolEvent("result", result=ToolResult("evidence_error"))
        return
    try:
        admission = operations.admission_status(request.task)
        if admission != "available":
            yield ToolEvent("result", result=ToolResult(admission))
            return
        prepared = _PreparedTask(
            deps,
            request.task,
            (request.repo,),
            request.run_ref_repos,
        )
        # Preparation progress is not backend discovery output.
        for _ in prepared.prepare(request.repo):
            pass
        context = prepared.context(request.repo)
        if (
            request.source_revision is not None
            and request.source_revision != context.source_revision
        ):
            yield ToolEvent("result", result=ToolResult("materialization_error"))
            return
        if request.host_tools_action == "bootstrap":
            yield from _bootstrap_host_tool_events(request, context, deps=deps)
            return
        if request.host_tools_action is not None:
            report = _host_tool_report(request, context, deps=deps)
            if report is None:
                yield ToolEvent("result", result=ToolResult("invalid"))
            else:
                yield ToolEvent("result", result=report)
            return
        host_tools_resolution = _resolve_host_tools_for_launch(
            request, context, deps=deps
        )
        if isinstance(host_tools_resolution, ToolResult):
            yield ToolEvent("result", result=host_tools_resolution)
            return
        if host_tools_resolution is None:
            yield ToolEvent("result", result=ToolResult("invalid"))
            return
        request = host_tools_resolution
        if request.preparation == "launch":
            setup_result = ToolResult("protocol_error")
            setup_stream = _setup_events(prepared, request.repo, context)
            try:
                for event in setup_stream:
                    if event.kind in {"stdout", "stderr"}:
                        yield event
                    elif event.kind == "result" and event.result is not None:
                        setup_result = event.result
            finally:
                setup_stream.close()
            if setup_result.status != "completed" or setup_result.exit_code != 0:
                status = (
                    setup_result.status
                    if setup_result.status != "completed"
                    else "launch_error"
                )
                yield ToolEvent("result", result=ToolResult(status))
                return
        publisher: TaskResultPublisher | None = None
        publish_result = None
        if task_key is not None:
            declaration = deps.config.repos[request.repo].task_outputs.get(task_key)
            if declaration is not None:
                if deps.result_store is None:
                    yield ToolEvent("result", result=ToolResult("evidence_error"))
                    return
                try:
                    publisher = TaskResultPublisher.prepare(
                        store=deps.result_store,
                        declaration=declaration,
                        context=context,
                        task_key=task_key,
                        output_parent=deps.workspace_root
                        / ".mothership"
                        / "task-output-roots",
                        work_item_id=(
                            None
                            if deps.work_item_id_for_task is None
                            else deps.work_item_id_for_task(request.task)
                        ),
                        provenance=deps.execution_provenance,
                    )
                except OSError, ValueError:
                    yield ToolEvent("result", result=ToolResult("evidence_error"))
                    return
                # Server-owned values overwrite untrusted request environment.
                request = replace(
                    request,
                    env={**request.env, **publisher.environment},
                )
                publish_result = publisher.publish
        stream = operations.run(
            request,
            context,
            cancel_event=deps.cancel_event,
            spawn=deps.shell.spawn_argv,
            publish_result=publish_result,
            session=session,
        )
        try:
            yield from stream
        finally:
            stream.close()
            if publisher is not None:
                publisher.cleanup()
    except _PreparationError as exc:
        yield ToolEvent("result", result=ToolResult(exc.status))
    except ShellCancelled:
        yield ToolEvent("result", result=ToolResult("cancelled"))
    except OSError, ValueError:
        yield ToolEvent("result", result=ToolResult("evidence_error"))
    finally:
        try:
            fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)
        finally:
            lock_file.close()


def source_owner_operation(
    operation: ToolRequest,
    owner: OwnerContext,
    name: str,
    payload: Mapping[str, object],
    *,
    deps: RemoteExecDeps,
) -> dict[str, object]:
    """Run one server-authenticated source handoff step, never a caller command."""
    stages = {
        "source-reserve": "reserved",
        "source-commit": "context-committed",
        "source-release": "reloaded",
        "source-abort": "aborted",
    }
    if name not in stages or owner.secret is None:
        raise SessionError("invalid", "Invalid framework source control")
    fields = {"update_id"}
    if name in {"source-reserve", "source-commit"}:
        fields.add("new_source_revision")
    data = strict_object(dict(payload), fields)
    update_id = identifier(data["update_id"])
    if (
        owner.task != operation.task
        or owner.repo != operation.repo
        or owner.owner_ref != operation.owner_ref
        or owner.generation != operation.generation
    ):
        raise SessionError("invalid", "Source control does not match recorded owner")
    if name == "source-release":
        found = _operations(deps).session_for_owner(
            task=owner.task,
            repo=owner.repo,
            owner_ref=owner.owner_ref,
            generation=owner.generation,
        )
        if found is None:
            raise SessionError("unknown", "Framework source owner is unavailable")
        current, inputs = found
        target = _decode_profile_json(inputs[TARGET_CONTEXT_FILE])
        task_keys = target.get("task_keys")
        if (
            not isinstance(task_keys, dict)
            or task_keys.get("reload") != operation.task_key
            or current.source_revision != owner.source_revision
        ):
            raise SessionError("invalid", "Source reload task does not match owner")
        request_body = _decode_profile_json(inputs[TARGET_REQUEST_FILE])
        request_body["operation"] = "reload"
        request = ToolRequest(
            task=owner.task,
            repo=owner.repo,
            argv=(),
            task_key=operation.task_key,
            input_files={
                TARGET_REQUEST_FILE: json.dumps(request_body, separators=(",", ":")),
                "MSHIP_SESSION_OPERATION_FILE": json.dumps(data, separators=(",", ":")),
            },
            preparation="observe",
            owner_ref=owner.owner_ref,
            generation=owner.generation,
            source_revision=current.source_revision,
        )
        stdout = bytearray()
        outcome = None
        reload_claim: OwnerRequest | None = None

        def prepared(context: OwnerContext) -> None:
            nonlocal reload_claim
            if context.request is None or context.request.operation != "source-release":
                raise SessionError("unknown", "Source reload authorization is missing")
            reload_claim = context.request

        events = run_tool_stream(
            request,
            deps=deps,
            source_update_id=update_id,
            owner_operation="source-release",
            on_session_prepared=prepared,
        )
        try:
            for event in events:
                if event.kind == "stdout":
                    if len(stdout) + len(event.data) > 64 * 1024:
                        raise SessionError(
                            "unknown", "Source reload acknowledgement is oversized"
                        )
                    stdout.extend(event.data)
                elif event.kind == "result":
                    outcome = event.result
        finally:
            events.close()
        if outcome is None or outcome.status != "completed" or outcome.exit_code != 0:
            raise SessionError("unknown", "Source reload was not acknowledged")
        if reload_claim is None:
            raise SessionError("unknown", "Source reload authorization is missing")
        owner.verify_source_reload(reload_claim, update_id)
        result = decode_private_json(bytes(stdout))
    else:
        request = OwnerRequest(
            operation_ref=secrets.token_urlsafe(24),
            operation=name,
            source_revision=owner.source_revision,
            expires_at=time.time() + CLAIM_TTL_SECONDS,
        )
        result = OwnerClient(owner.issue(request)).call(
            name,
            data,
            cancel_event=deps.cancel_event,
            timeout=30,
        )
    if result != {"update_id": update_id, "stage": stages[name]}:
        raise SessionError("unknown", "Source control acknowledgement does not match")
    return result


def run_observe_capture_stream(
    operation: ToolRequest,
    *,
    deps: RemoteExecDeps,
    kinds: Sequence[str],
    platform: str,
    nonce: str,
) -> Generator[bytes, None, None]:
    """Capture through one existing owner without preparing any source or app."""
    capture_directory: Path | None = None
    capture_fd: int | None = None
    capture_parent_fd: int | None = None
    capture_authority: tuple[OwnerContext, OwnerRequest] | None = None

    def prepared(context: OwnerContext) -> None:
        nonlocal capture_directory, capture_fd, capture_parent_fd
        nonlocal capture_authority
        request = context.request
        if request is None or request.operation != "capture" or request.capture is None:
            raise SessionError("invalid", "Missing owner capture grant")
        parent = _operations(deps).session_for_owner(
            task=context.task,
            repo=context.repo,
            owner_ref=context.owner_ref,
            generation=context.generation,
        )
        if parent is None:
            raise SessionError("unknown", "Capture parent is no longer available")
        capture_authority = (parent[0], request)
        capture_directory = request.capture.directory
        capture_parent_fd = os.open(
            capture_directory.parent,
            os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW,
        )
        capture_fd = os.open(
            capture_directory.name,
            os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW,
            dir_fd=capture_parent_fd,
        )
        info = os.fstat(capture_fd)
        if info.st_uid != os.geteuid() or info.st_mode & 0o077:
            raise SessionError("unknown", "Capture grant directory is not private")

    def cleanup() -> bool:
        nonlocal capture_fd, capture_parent_fd
        descriptor, parent_descriptor = capture_fd, capture_parent_fd
        capture_fd = capture_parent_fd = None
        if descriptor is None:
            if parent_descriptor is not None:
                os.close(parent_descriptor)
            return True
        assert capture_directory is not None and parent_descriptor is not None
        known = True
        try:
            # Outputs are flat. Never recursively remove unexpected directories.
            with os.scandir(descriptor) as entries:
                for entry in entries:
                    if entry.is_dir(follow_symlinks=False):
                        known = False
                    else:
                        os.unlink(entry.name, dir_fd=descriptor)
            expected = os.fstat(descriptor)
            actual = os.stat(
                capture_directory.name, dir_fd=parent_descriptor, follow_symlinks=False
            )
            if (actual.st_dev, actual.st_ino) != (expected.st_dev, expected.st_ino):
                return False
            os.rmdir(capture_directory.name, dir_fd=parent_descriptor)
            parent_info = os.fstat(parent_descriptor)
            current_parent = capture_directory.parent.stat(follow_symlinks=False)
            if (current_parent.st_dev, current_parent.st_ino) != (
                parent_info.st_dev,
                parent_info.st_ino,
            ):
                return False
            capture_directory.parent.rmdir()
        except OSError:
            known = False
        finally:
            os.close(descriptor)
            os.close(parent_descriptor)
        return known

    code = 1
    try:
        if (
            operation.preparation != "observe"
            or operation.task_key is None
            or operation.argv
            or operation.install_from_result is not None
            or platform not in {"android", "ios"}
            or not kinds
            or len(kinds) > 2
            or len(set(kinds)) != len(kinds)
            or any(kind not in _cap.ALL_KINDS for kind in kinds)
        ):
            raise SessionError("invalid", "Invalid session capture request")
        result = None
        events = run_tool_stream(
            operation,
            deps=deps,
            capture_kinds=tuple(kinds),
            capture_platform=platform,
            on_session_prepared=prepared,
        )
        try:
            for event in events:
                if event.kind == "result":
                    result = event.result
        finally:
            events.close()
        if result is None or result.status != "completed" or result.exit_code != 0:
            raise SessionError("unavailable", "Session capture was not acknowledged")
        if capture_directory is None or capture_fd is None:
            raise SessionError("unknown", "Session capture grant is unavailable")
        expected = os.fstat(capture_fd)
        actual = capture_directory.stat(follow_symlinks=False)
        if (actual.st_dev, actual.st_ino) != (expected.st_dev, expected.st_ino):
            raise SessionError("unknown", "Session capture directory changed")
        artifacts = _cap.discover_artifacts(capture_directory, list(kinds))
        if {artifact.kind for artifact in artifacts} != set(kinds):
            raise SessionError(
                "unavailable", "Session capture omitted a requested artifact"
            )
        if capture_authority is None:
            raise SessionError(
                "unknown", "Capture owner acknowledgement is unavailable"
            )
        authority, capture_request = capture_authority
        manifest = authority.verify_capture(capture_request)
        if set(manifest) != {artifact.path.name for artifact in artifacts}:
            raise SessionError("unknown", "Capture artifact identity changed")
        data = _build_artifact_tar(
            artifacts,
            directory_fd=capture_fd,
            max_bytes=256 * 1024 * 1024,
            expected_artifacts=manifest,
        )
        if not cleanup():
            raise SessionError(
                "unknown", "Session capture output cleanup is incomplete"
            )
        yield f"{ARTIFACT_MARKER}:{nonce} {len(data)}\n".encode()
        yield data
        code = 0
    except OSError, ValueError, SessionError:
        yield b"error: selected session capture or artifact validation failed\n"
    finally:
        cleanup()
    yield f"{EXIT_MARKER}:{nonce} {code}\n".encode()
