version: '3'

tasks:
  targets:
    silent: true
    cmds:
      - '"{{.MSHIP_SESSION_PYTHON}}" backend.py discover'
  monitor:
    silent: true
    cmds:
      - '"{{.MSHIP_SESSION_PYTHON}}" backend.py'
  logs:
    silent: true
    cmds:
      - '"{{.MSHIP_SESSION_PYTHON}}" backend.py'
  upload:
    silent: true
    cmds:
      - '"{{.MSHIP_SESSION_PYTHON}}" backend.py'
